### ISSUE TITLE
remote control not working on android tv version 4.7.0.0

### ISSUE THREAD

**Issue by weirdmo** [amnezia-vpn/amnezia-client#1001]
tv remote control not working on new version on android tv
I have to use mouse to be able to turn vpn on or off

tv is tcl with android version 11
app is 4.7.0.0 manually installed apk from github

**Comment by DrCorvax** [comment]
I've got same problem on Xiaomi TV A4.

**Comment by sbh96** [comment]
I've got same problem on sony tv (google tv)

**Comment by r4tz52** [comment]
Same here with TCL 55C755 Android TV.

**Comment by albexk** [comment]
Fixed here #1143
