### ISSUE TITLE
Error 300 on correct data

### ISSUE THREAD

**Issue by Gotoro** [amnezia-vpn/amnezia-client#1013]
**Describe the bug**
Adding personal server, with non standard ssh port, disabled root login (meaning that I'm using different name for user).
This looks like, for example:

Server IP address [:port]
`80.70.60.50:60606`

SSH username
`newuser`

Password
`correctpassword`

The server adds correctly, but I can't install protocols, getting Error 300.
This happened after I tried to change amnezia to use new reconfigured port and username, after I changed them. I can connect with ssh with provided data just fine.

**To Reproduce**
1. Add new server
2. Enter ip address with non standard port
3. Enter non-root username
4. Enter correct password

**Expected behavior**
I expect to download the protocol and not get "incorrect data" error, as the server itself adds correctly.

**Log files**
I can attach them later.

**Screenshots**
Can't take screenshots of the mobile app

**Smartphone (please complete the following information):**
 - Device: Poco M6 Pro
 - OS: Android 14 + HyperOS 1.0.4.0
 - Version: 4.7.0.0

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS x86_64

**Comment by Gotoro** [comment]
After reading logs, I guessed that the file permissions are borked. For anyone with similar situation, found a solution.

`/opt/amnezia/` contains Dockerfiles for building amnezia protocols. As previous files were owned by now disabled root, and that apparently Amnezia didn't use sudo in this case of getting dockerfiles, I've changed groups and permissions of all the folders in the aforementioned directories:
```
sudo chgrp -R $USER ./opt/amnezia/*
sudo chmod g+rwx -R ./opt/amnezia/*
cd /opt/amnezia/
ls -l
```

**Comment by m1a2023** [comment]
I had the same error and tried to resolve it changing directory `/opt/AmneziaVpn` rights. 
But got the same `ErrorCode: 300 SSH ...`. 

I use newest protocol AmneziaWG (version 2.0). Most likely my version of AmneziaVpn application didn't supported this protocol. 

To solve this issue install the newest version of AmneziaVPN application
