### ISSUE TITLE
Sometimes AmneziaWG didn't complete handshakes

### ISSUE THREAD

**Issue by kda2495** [amnezia-vpn/amnezia-client#1041]
**Describe the bug**
I use AmneziaWG on iOS and Windows with Cloudflare WARP. Sometimes when I connect, I don't have connection. In log files I see message: Sending handshake initiation and then Handshake did not complete aftr 5 seconds, retrying. I changed Jc, Jmin, Jmax and other integers but it doesn't help. Sometimes it works, but sometimes not. Can you fix it?

**To Reproduce**
1. Go to 'Amnezia WG'
2. Click on 'Connect'
3. No completion of handshake sometimes

**Expected behavior**
Handshake completion every time I connect.

**Log files**
Attach log files to help explain your problem.

**Screenshots**
![photo_5384155351861029283_y](https://github.com/user-attachments/assets/80b9e958-b4aa-4389-898b-9fcec9d5a9ea)

**Desktop (please complete the following information):**
 - OS:, Windows 7 SP1
 - Version [e.g. 1.0.0]

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 16
 - Version 1.0.1 (6)

**Comment by kda2495** [comment]
I used many settings, many VPN providers and problem exists. I don't know why, but sometimes handshake doesn't complete.

**Comment by amnzam** [comment]
Hello. Thank you for your message. 
Could you please clarify some statements from your message? 
1. The issue appears more on Cellular data (internet) or Home (ISP) internet? Is it the same with all providers?
2. What do you mean by this: > many VPN providers and problem exists
3. Am I right that you are using WARP config with AmneziaWG app?

**Comment by kda2495** [comment]
> Hello. Thank you for your message. Could you please clarify some statements from your message?
> 
> 1. The issue appears more on Cellular data (internet) or Home (ISP) internet? Is it the same with all providers?
> 2. What do you mean by this: > many VPN providers and problem exists
> 3. Am I right that you are using WARP config with AmneziaWG app?

1.  Cellular and Home, the same.
2. Many VPN-providers (Cloudflare WARP, ProtonVPN and others) with Wireguard-configs and AmneziaWG-improvements.
3. Wireguard-config with AmneziaWG-improvements (Jc and others) in AmneziaWG for iOS and Windows.
90% of connections is successful, but I have problem with handshake in 10% of connections.
To reproduce this you can make config and connect-disable connect-connect again and sometimes you will see, that internet is down and in journal you'll see, that handshake isn't successful. Hope, you will find this and fix. Thanks!

**Comment by amnzam** [comment]
@kda2495 
Am I right that you are using self-hosted solution for AWG protocol? 
Did you try to install and connect to any VPS server with AWG protocol through AmneziaVPN app?

**Comment by kda2495** [comment]
> @kda2495
> Am I right that you are using self-hosted solution for AWG protocol?
> Did you try to install and connect to any VPS server with AWG protocol through AmneziaVPN app?

I've updated my comment from above. No, I haven't tried using any VPS server, just some free VPN-providers. If it is a problem with Cloudflare WARP, so, why it exists with ProtonVPN Wireguard config also?

**Comment by amnzam** [comment]
> > @kda2495
> > Am I right that you are using self-hosted solution for AWG protocol?
> > Did you try to install and connect to any VPS server with AWG protocol through AmneziaVPN app?
> 
> I've updated my comment from above. No, I haven't tried using any VPS server, just some free VPN-providers. If it is a problem with Cloudflare WARP, so, why it exists with ProtonVPN Wireguard config also?

Because of DPI in Russia. They are trying to block Wireguard protocol and all VPN providers. We suggest you to try AWG self-hosted solution.

**Comment by kda2495** [comment]
> > > @kda2495
> > > Am I right that you are using self-hosted solution for AWG protocol?
> > > Did you try to install and connect to any VPS server with AWG protocol through AmneziaVPN app?
> > 
> > 
> > I've updated my comment from above. No, I haven't tried using any VPS server, just some free VPN-providers. If it is a problem with Cloudflare WARP, so, why it exists with ProtonVPN Wireguard config also?
> 
> Because of DPI in Russia. They are trying to block Wireguard protocol and all VPN providers. We suggest you to try AWG self-hosted solution.

It's strange, that 90% of connections is successful. Isn't it the problem with the AmneziaWG app?

**Comment by amnzam** [comment]
> > > > @kda2495
> > > > Am I right that you are using self-hosted solution for AWG protocol?
> > > > Did you try to install and connect to any VPS server with AWG protocol through AmneziaVPN app?
> > > 
> > > 
> > > I've updated my comment from above. No, I haven't tried using any VPS server, just some free VPN-providers. If it is a problem with Cloudflare WARP, so, why it exists with ProtonVPN Wireguard config also?
> > 
> > 
> > Because of DPI in Russia. They are trying to block Wireguard protocol and all VPN providers. We suggest you to try AWG self-hosted solution.
> 
> It's strange, that 90% of connections is successful.

What do you mean by this?

**Comment by kda2495** [comment]
> > > > > @kda2495
> > > > > Am I right that you are using self-hosted solution for AWG protocol?
> > > > > Did you try to install and connect to any VPS server with AWG protocol through AmneziaVPN app?
> > > > 
> > > > 
> > > > I've updated my comment from above. No, I haven't tried using any VPS server, just some free VPN-providers. If it is a problem with Cloudflare WARP, so, why it exists with ProtonVPN Wireguard config also?
> > > 
> > > 
> > > Because of DPI in Russia. They are trying to block Wireguard protocol and all VPN providers. We suggest you to try AWG self-hosted solution.
> > 
> > 
> > It's strange, that 90% of connections is successful.
> 
> What do you mean by this?

When I use any config with AmneziaWG 90% of handshakes (connect-disable connect-reconnect) is successful. But handshake isn't successful with 10% of connections. So, is that mean, that problem can be with AmneziaWG?

**Comment by amnzam** [comment]
What 

> > > > > > @kda2495
> > > > > > Am I right that you are using self-hosted solution for AWG protocol?
> > > > > > Did you try to install and connect to any VPS server with AWG protocol through AmneziaVPN app?
> > > > > 
> > > > > 
> > > > > I've updated my comment from above. No, I haven't tried using any VPS server, just some free VPN-providers. If it is a problem with Cloudflare WARP, so, why it exists with ProtonVPN Wireguard config also?
> > > > 
> > > > 
> > > > Because of DPI in Russia. They are trying to block Wireguard protocol and all VPN providers. We suggest you to try AWG self-hosted solution.
> > > 
> > > 
> > > It's strange, that 90% of connections is successful.
> > 
> > 
> > What do you mean by this?
> 
> When I use any config with AmneziaWG 90% of handshakes (connect-disable connect-reconnect) is successful. But handshake isn't successful with 10% of connections. So, is that mean, that problem can be with AmneziaWG?

As I understood, you are using Wireguard protocol configs of different VPN providers. As I have told you before, Russian DPI software/hardware is trying to block Wireguard protocol and all VPN providers. We suggest you try AWG protocol. AWG has been created on top of Wireguard with some obfuscation features.

**Comment by kda2495** [comment]
> What
> 
> > > > > > > @kda2495
> > > > > > > Am I right that you are using self-hosted solution for AWG protocol?
> > > > > > > Did you try to install and connect to any VPS server with AWG protocol through AmneziaVPN app?
> > > > > > 
> > > > > > 
> > > > > > I've updated my comment from above. No, I haven't tried using any VPS server, just some free VPN-providers. If it is a problem with Cloudflare WARP, so, why it exists with ProtonVPN Wireguard config also?
> > > > > 
> > > > > 
> > > > > Because of DPI in Russia. They are trying to block Wireguard protocol and all VPN providers. We suggest you to try AWG self-hosted solution.
> > > > 
> > > > 
> > > > It's strange, that 90% of connections is successful.
> > > 
> > > 
> > > What do you mean by this?
> > 
> > 
> > When I use any config with AmneziaWG 90% of handshakes (connect-disable connect-reconnect) is successful. But handshake isn't successful with 10% of connections. So, is that mean, that problem can be with AmneziaWG?
> 
> As I understood, you are using Wireguard protocol configs of different VPN providers. As I have told you before, Russian DPI software/hardware is trying to block Wireguard protocol and all VPN providers. We suggest you try AWG protocol. AWG has been created on top of Wireguard with some obfuscation features.

No, you've understood wrong) So, for example, I make a config of Cloudflare WARP, then I modify it with Jc = 3, Jmin = 40, Jmax = 70 and other recommendated integers. Then I import it in AmneziaWG app and everything works in 90 percents (handshake is successful). But sometimes, when I connect with AmneziaWG, handshake don't complete. I don't use Wireguard, only AmneziaWG apps for iOS and Windows.

**Comment by kda2495** [comment]
![Безымянный](https://github.com/user-attachments/assets/39096cf8-81d1-486b-a4d6-d86d74c5c4e3)
This is what I see on AmneziaWG on Windows. To reproduce this, you should connect-disconnect-connect for some time (10 maybe). And you will see, that AmneziaWG tries to make handshake with server and didn't complete it. If you want, I can make config of Cloudflare WARP to test and reproduce this bug. Also I see this bug on iOS with AmneziaWG app.

**Comment by amnzam** [comment]
> ![Безымянный](https://private-user-images.githubusercontent.com/140339869/364336062-39096cf8-81d1-486b-a4d6-d86d74c5c4e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDU4NzcsIm5iZiI6MTcyNTQ0NTU3NywicGF0aCI6Ii8xNDAzMzk4NjkvMzY0MzM2MDYyLTM5MDk2Y2Y4LTgxZDEtNDg2Yi1hNGQ2LWQ4NmQ3NGM1YzRlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMDI2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWY3ZWNkMGY0YWQ5NTEzNmNjMGNiODE1YjhiY2RmMmIwNzY4OTM1YjdkNTc4YTUwNmY0MjhjZWY2ZDQwNjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OWfONaB2lda7C9xbYGiC-uyZyFIZJqDXL5AhNMKQQ2E) This is what I see on AmneziaWG on Windows. To reproduce this, you should connect-disconnect-connect for some time (10 maybe). And you will see, that AmneziaWG tries to make handshake with server and didn't complete it. If you want, I can make config of Cloudflare WARP to test and reproduce this bug. Also I see this bug on iOS with AmneziaWG app.

Did you try native AWG protocol?

**Comment by kda2495** [comment]
So, I've fixed it. Maybe it will be help:
When you connect to any server it generates ListenPort. With Cloudflare WARP ListenPort is random. When my ListenPort is 60060, 65008 and some others it doesn't make handshakes. But when I changed in my .conf file string ListenPort to 63399, it works and all handshakes complete.
So, if you have problem like peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds, you should hardcode a port to listen (such as 63399)

**Comment by crwnhdd** [comment]
> So, I've fixed it. Maybe it will be help: When you connect to any server it generates ListenPort. With Cloudflare WARP ListenPort is random. When my ListenPort is 60060, 65008 and some others it doesn't make handshakes. But when I changed in my .conf file string ListenPort to 63399, it works and all handshakes complete. So, if you have problem like peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds, you should hardcode a port to listen (such as 63399)

Hello. I'm having the same trouble as you, but sadly I'm not really into any of that. Could you please tell how to change the ListenPort? I didn't find it in the WARP.conf file and when editing the warp in AWG

**Comment by kda2495** [comment]
> > So, I've fixed it. Maybe it will be help: When you connect to any server it generates ListenPort. With Cloudflare WARP ListenPort is random. When my ListenPort is 60060, 65008 and some others it doesn't make handshakes. But when I changed in my .conf file string ListenPort to 63399, it works and all handshakes complete. So, if you have problem like peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds, you should hardcode a port to listen (such as 63399)
> 
> Hello. I'm having the same trouble as you, but sadly I'm not really into any of that. Could you please tell how to change the ListenPort? I didn't find it in the WARP.conf file and when editing the warp in AWG

In your .conf-file in the [Interface] group just add string ListenPort = 51820 (or any other random value from 50000 to 65000)

**Comment by Tasmanskiu** [comment]
> > > So, I've fixed it. Maybe it will be help: When you connect to any server it generates ListenPort. With Cloudflare WARP ListenPort is random. When my ListenPort is 60060, 65008 and some others it doesn't make handshakes. But when I changed in my .conf file string ListenPort to 63399, it works and all handshakes complete. So, if you have problem like peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds, you should hardcode a port to listen (such as 63399)
> > 
> > 
> > Hello. I'm having the same trouble as you, but sadly I'm not really into any of that. Could you please tell how to change the ListenPort? I didn't find it in the WARP.conf file and when editing the warp in AWG
> 
> In your .conf-file in the [Interface] group just add string ListenPort = 51820 (or any other random value from 50000 to 65000)

I followed your instructions to the letter.
I've tried all the suggestions you made, but I'm still having trouble. I'd really appreciate your help with this.
I've attached the screenshots below in case they're helpful.

I've tried different values, from 50000 to 65000, but when I turn it on, the internet doesn't work at all. 

Once I installed the program and ran the config, everything worked great. However, after a few days, this error popped up, and it's been an ongoing issue ever since. 

![Amnezia 1](https://github.com/user-attachments/assets/ab688b33-425c-4b08-9079-dffdae80e2ac)
![Amnezia 2](https://github.com/user-attachments/assets/0853d81b-b4de-400f-bd57-a63e566657a9)

**Comment by kda2495** [comment]
> > > > So, I've fixed it. Maybe it will be help: When you connect to any server it generates ListenPort. With Cloudflare WARP ListenPort is random. When my ListenPort is 60060, 65008 and some others it doesn't make handshakes. But when I changed in my .conf file string ListenPort to 63399, it works and all handshakes complete. So, if you have problem like peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds, you should hardcode a port to listen (such as 63399)
> > > 
> > > 
> > > Hello. I'm having the same trouble as you, but sadly I'm not really into any of that. Could you please tell how to change the ListenPort? I didn't find it in the WARP.conf file and when editing the warp in AWG
> > 
> > 
> > In your .conf-file in the [Interface] group just add string ListenPort = 51820 (or any other random value from 50000 to 65000)
> 
> I followed your instructions to the letter. I've tried all the suggestions you made, but I'm still having trouble. I'd really appreciate your help with this. I've attached the screenshots below in case they're helpful.
> 
> I've tried different values, from 50000 to 65000, but when I turn it on, the internet doesn't work at all.
> 
> Once I installed the program and ran the config, everything worked great. However, after a few days, this error popped up, and it's been an ongoing issue ever since.
> 
> ![Amnezia 1](https://private-user-images.githubusercontent.com/104103745/377265092-ab688b33-425c-4b08-9079-dffdae80e2ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDAwNzksIm5iZiI6MTcyOTEzOTc3OSwicGF0aCI6Ii8xMDQxMDM3NDUvMzc3MjY1MDkyLWFiNjg4YjMzLTQyNWMtNGIwOC05MDc5LWRmZmRhZTgwZTJhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNDM2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTM0NGJiYmMyNTlmYTk4MmZiYzkxYjIxMzMxMTc4ZmM5MWU0ZTFkMmI2N2I1YTNiN2M4ZjRjNGVjYzAwZWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nCiHXmhdyep7pEEPxu_zb3ufChDimVbR1UNifwdNT5o) ![Amnezia 2](https://private-user-images.githubusercontent.com/104103745/377265095-0853d81b-b4de-400f-bd57-a63e566657a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDAwNzksIm5iZiI6MTcyOTEzOTc3OSwicGF0aCI6Ii8xMDQxMDM3NDUvMzc3MjY1MDk1LTA4NTNkODFiLWI0ZGUtNDAwZi1iZDU3LWE2M2U1NjY2NTdhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNDM2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTlmN2QzOGFhYTE1OWQ4YTcxMTIzYzlhNWM2MzBiYTIxNjg2NTIxNTQ4OTYwNzRjMWMxNzg3NTRlYTFhMGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XAq78hO-zAumkOdFvbe0OeKGeHrVp3pT0GgUGe9ihFY)

Напиши в телеграм: t.me/kda2495

**Comment by maxkusnetsov** [comment]
> > > > So, I've fixed it. Maybe it will be help: When you connect to any server it generates ListenPort. With Cloudflare WARP ListenPort is random. When my ListenPort is 60060, 65008 and some others it doesn't make handshakes. But when I changed in my .conf file string ListenPort to 63399, it works and all handshakes complete. So, if you have problem like peer(bmXO…fgyo) - Retrying handshake because we stopped hearing back after 15 seconds, you should hardcode a port to listen (such as 63399)
> > > 
> > > 
> > > Hello. I'm having the same trouble as you, but sadly I'm not really into any of that. Could you please tell how to change the ListenPort? I didn't find it in the WARP.conf file and when editing the warp in AWG
> > 
> > 
> > In your .conf-file in the [Interface] group just add string ListenPort = 51820 (or any other random value from 50000 to 65000)
> 
> I followed your instructions to the letter. I've tried all the suggestions you made, but I'm still having trouble. I'd really appreciate your help with this. I've attached the screenshots below in case they're helpful.
> 
> I've tried different values, from 50000 to 65000, but when I turn it on, the internet doesn't work at all.
> 
> Once I installed the program and ran the config, everything worked great. However, after a few days, this error popped up, and it's been an ongoing issue ever since.
> 
> ![Amnezia 1](https://private-user-images.githubusercontent.com/104103745/377265092-ab688b33-425c-4b08-9079-dffdae80e2ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNjYwOTAsIm5iZiI6MTczMTI2NTc5MCwicGF0aCI6Ii8xMDQxMDM3NDUvMzc3MjY1MDkyLWFiNjg4YjMzLTQyNWMtNGIwOC05MDc5LWRmZmRhZTgwZTJhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxOTA5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTdlNzZmMjY2MzkzMzc0ZDQwOGI4OWJiMGY1NjYwNjE4MGIzOGRkODgxZTE2NGZmYWU3NmViNzg5YjUyYjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eUYq5tmxYv-kzhPNz6wVt6rfQBKnlPdxz4QWHiXOpm4) ![Amnezia 2](https://private-user-images.githubusercontent.com/104103745/377265095-0853d81b-b4de-400f-bd57-a63e566657a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNjYwOTAsIm5iZiI6MTczMTI2NTc5MCwicGF0aCI6Ii8xMDQxMDM3NDUvMzc3MjY1MDk1LTA4NTNkODFiLWI0ZGUtNDAwZi1iZDU3LWE2M2U1NjY2NTdhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxOTA5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTA3NDIyNWQwMGQzMmQxMjI0NjdlNjA3NjNhZGJlMTI3Mjk5ZTY3NTY1ZWE4ZDcxMmEyM2Q1N2VkMTk4YjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OanC1CCj1rTmFsnpuN6A2ICbeFUFwFamyx2ivU37W5c)

Hi, were you able to resolve this issue?

**Comment by Luminisc** [comment]
Similar issue for last 2 days :(  
Tried different ListenPorts, Jc/Jmax/Jmin - nothing helps
![image](https://github.com/user-attachments/assets/bb99b1af-e3b9-4b00-9cb5-27b6fbf17363)

**Comment by SlendyCandy** [comment]
The issue is back (at least for Russia) it worked and then suddenly it popped off and doesn't work anymore on any port

**Comment by l4kt0Bionic** [comment]
I recently had a power outage + problems with internet connection with Wi-Fi router
I also turned on and off my configs on AWG while attempting to resolve an issue
After that, I began to have an issue with handshakes
The only time when I received my handshake was _yesterday_, and everything worked fine until today when handshakes weren't completed as intended
If anyone knows how to help, please, approach me!
Thank you in advance...

**Comment by l4kt0Bionic** [comment]
> I recently had a power outage + problems with internet connection with Wi-Fi router I also turned on and off my configs on AWG while attempting to resolve an issue After that, I began to have an issue with handshakes The only time when I received my handshake was _yesterday_, and everything worked fine until today when handshakes weren't completed as intended If anyone knows how to help, please, approach me! Thank you in advance...

I'm gonna give you some more details in case you wonder:
I'm using W10 Home, AmneziaWG (1.0.2.) and free ProtonVPN's tunnel configurations (which don't work right now due to handshakes not being completed)
Upd: I only receive 92 bytes of packets when connected to one of them while sending lots of kbs of packets to server

**Comment by 9564519** [comment]
The problem is still relevant.

**Comment by 9564519** [comment]
<img width="946" height="318" alt="Image" src="https://github.com/user-attachments/assets/9ceb993c-90a3-422b-b2a1-ea6439c92215" /> 

я использовал скрипт, и перебирал многие порты, но безуспешно
```ps1
$wgIP = "162.159.192.1"
$wgPORT = 500

# Автоматический выбор свободного порта
$wgListenPort = 0

try {
    $EndPoints = New-Object System.Net.IPEndPoint([System.Net.IPAddress]::Parse([System.Net.Dns]::GetHostAddresses($wgIP)), $wgPORT) 
    $Socket = New-Object System.Net.Sockets.UDPClient $wgListenPort
    
    # Получаем фактический порт, который был выбран системой
    $actualPort = $Socket.Client.LocalEndPoint.Port
    $SendMessage = $Socket.Send([Text.Encoding]::ASCII.GetBytes("123"), 2, $EndPoints)
    
    Write-Host "Пакет успешно отправлен!" -ForegroundColor Green
    Write-Host "Локальный порт: $actualPort" -ForegroundColor Cyan
    Write-Host "Удаленный адрес: $wgIP`:$wgPORT" -ForegroundColor Cyan
    
    $Socket.Close()
    
    # Возвращаем порт для использования в других программах
    $actualPort
}
catch {
    Write-Host "Ошибка: $($_.Exception.Message)" -ForegroundColor Red
}
```

**Comment by amnzam** [comment]
> <img alt="Image" width="946" height="318" src="https://private-user-images.githubusercontent.com/54405203/506066261-9ceb993c-90a3-422b-b2a1-ea6439c92215.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE1NzcxNDcsIm5iZiI6MTc2MTU3Njg0NywicGF0aCI6Ii81NDQwNTIwMy81MDYwNjYyNjEtOWNlYjk5M2MtOTBhMy00MjJiLWIyYTEtZWE2NDM5YzkyMjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI3VDE0NTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YmNhNTI3NDM5YjI0Mzg1Y2Q2MTYzOGI0MGY0YmQxYWUxZjc4OTdjMGM0NTg3Yjg1MjkyNjYxNGNjMGYzN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c7bR05OAIisYHi2cfJa81_vpuGjLDkjRyFtZr_BwXRI">
> я использовал скрипт, и перебирал многие порты, но безуспешно
> 
> $wgIP = "162.159.192.1"
> $wgPORT = 500
> 
> # Автоматический выбор свободного порта
> $wgListenPort = 0
> 
> try {
>     $EndPoints = New-Object System.Net.IPEndPoint([System.Net.IPAddress]::Parse([System.Net.Dns]::GetHostAddresses($wgIP)), $wgPORT) 
>     $Socket = New-Object System.Net.Sockets.UDPClient $wgListenPort
>     
>     # Получаем фактический порт, который был выбран системой
>     $actualPort = $Socket.Client.LocalEndPoint.Port
>     $SendMessage = $Socket.Send([Text.Encoding]::ASCII.GetBytes("123"), 2, $EndPoints)
>     
>     Write-Host "Пакет успешно отправлен!" -ForegroundColor Green
>     Write-Host "Локальный порт: $actualPort" -ForegroundColor Cyan
>     Write-Host "Удаленный адрес: $wgIP`:$wgPORT" -ForegroundColor Cyan
>     
>     $Socket.Close()
>     
>     # Возвращаем порт для использования в других программах
>     $actualPort
> }
> catch {
>     Write-Host "Ошибка: $($_.Exception.Message)" -ForegroundColor Red
> }

Hello.
As I can see, you are using Cloudflare IP address to connect, I assume that it's IP address of their service Cloudflare Warp. Please make sure that this IP address is accessible (is not filtered or blocked) from your side.
