### ISSUE TITLE
feedback regarding the Errorcode: 1100 

### ISSUE THREAD

**Issue by mat48** [amnezia-vpn/amnezia-client#1071]
I'm trying to figure out if there's any way I can help and fix the error 1100, but I need more information about the key's functionality on how it fetches the main keys. As I'm not a tech expert, could you provide info on how the initial key that contains a "vpn:/.." connection link turns into the main key that the app uses? 

if not, here's the feedback, appreciate your hard work on the app. have a nice day :)

---

since yesterday which I enountered the 1100 error:

- I tested the "vpn:/.." connection link in various devices solotions that did not work:
	- reinstalling the app
	- installing old versions
	- using new connection links from telegram bots [with a different account ofc]
	- using airplane mode [on phones]
	- restarting [the phones]
	- resetting api configuration
	
- solotion that works:
	- using a phone that has a working server to backup the already_working_key and use that already_working_key_BACKUP on other devices. (and just for the record, when a new_faulty_key is used on the working device the new server produces the 1100 error code and when we switch the server back to the already_working_key it works perfectly.)
	
- sugguested solotion:
	- is there any method that we can modify the already_working_key_BACKUP using the values provided in the new_faulty_key?

**Desktop (please complete the following information):**
	- Latest version

**Smartphone (please complete the following information):**
	- Device: [android]
	- Latest version

**Comment by mat48** [comment]
- another possible solution: 
  - is there the possibility to implement a method to receive the key from the telegram bot in .BACKUP format, containing the values that normally the users should receive after their first connection?

**Comment by Nethius** [comment]
https://docs.amnezia.org/troubleshooting/error-codes#error-1100-apiconfigdownloaderror

**Comment by mat48** [comment]
I read and tried all of those solutions plus the ones that the support is suggesting in the telegram group but none of them worked !

**Comment by papampi** [comment]
Still not fixed 😞
