### ISSUE TITLE
Broken UI scale for squared screens on Android

### ISSUE THREAD

**Issue by hooddy** [amnezia-vpn/amnezia-client#1105]
On my Unihertz titan phone with square screen UI scale is broken since versions higher 4.7.0.0. Please bring it back.
![photo_2024-10-01_09-28-37](https://github.com/user-attachments/assets/b712decc-f918-4a9c-9e75-7c991fedcab9)

**Comment by pokamest** [comment]
Please check latest 4.8 release

**Comment by hooddy** [comment]
> Please check latest 4.8 release

It's the same. Screenshot from v4.8.1.8

**Comment by Nethius** [comment]
try this branch https://github.com/amnezia-vpn/amnezia-client/actions/runs/11130343339

**Comment by albexk** [comment]
Fixed here #1143
