### ISSUE TITLE
Split tunneling of applications on PC does not work

### ISSUE THREAD

**Issue by crcdakeyras** [amnezia-vpn/amnezia-client#1106]
**Describe the bug**
Split tunneling of applications on PC does not work 50%.
You can set which "applications should not work through VPN", but you cannot select the setting "applications that should work through VPN", which in my opinion is much more important.

On Android you can select this setting, but not on PC.

**To Reproduce**
1. Go to 'Split VPN Tunneling'
2. Click on 'Split Application Tunneling'
3. Drop-down menus with the choice "should/should not work via vpn" - inactive

**Expected behavior**
I expected that I would be able to set up a mode like on Android where I could specify "which applications need to access the Internet via VPN"

**Log files**
please see screenshot below

**Screenshots**
![image](https://github.com/user-attachments/assets/061151a1-5663-419a-b1d7-2177be37cc75)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 22H2

**Server (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
Please sort out this bug or at least explain why it is the way it is now.
p.s. tried 4.7.0 version of amnesia and 4.8.1

**Comment by Nethius** [comment]
in windows, you can only use the “Apps from the list should not have access via VPN” mode. These are the specifics of the tunneling implementation on this platform

**Comment by Gerasash** [comment]
also disable killswitch(on the bottom side in menu) function in settings->connections ,
