### ISSUE TITLE
Feature request: using glob patterns for split tunneling

### ISSUE THREAD

**Issue by eugene-beliaev** [amnezia-vpn/amnezia-client#1114]
I personally really miss (and I believe not only me) the ability to keep VPN off for visiting websites in ".ru" domain zone and at the same time keep VPN on for all other websites. My suggestion is to support glob-patterns while using split-tunneling. Is it possible to implement?

**Comment by samdark** [comment]
Same as https://github.com/amnezia-vpn/amnezia-client/issues/856?

**Comment by eugene-beliaev** [comment]
Exactly! Thank you
