### ISSUE TITLE
The "Users" section does not load from a smartphone

### ISSUE THREAD

**Issue by unrie** [amnezia-vpn/amnezia-client#1116]
After updating the application to version 4.8.1.9, the users section (endless download) stopped opening through the play store. Smartphone Redmi Note 10S (Android 13). What could be the problem?

**Comment by unrie** [comment]
Rolling back to version 4.7.0.0 helped.

**Comment by unrie** [comment]
Rolling back to version 4.7.0.0 helped.

**Comment by Nethius** [comment]
can u try this branch please? https://github.com/amnezia-vpn/amnezia-client/pull/1119
