### ISSUE TITLE
Cant install on UBUNTU

### ISSUE THREAD

**Issue by ja49619** [amnezia-vpn/amnezia-client#1118]
**Describe the bug**
Cant install on UBUNTU

**To Reproduce**
1. Go to [main page](https://github.com/amnezia-vpn/amnezia-client)
2. Download for [linux](https://github.com/amnezia-vpn/amnezia-client/releases/download/4.7.0.0/AmneziaVPN_Linux_4.7.0.0.tar.zip)
3. Try to install

```
serv:~/amnezia/AmneziaVPN_Linux_4.7.0.0$ tar -xf  AmneziaVPN_Linux_Installer.tar 
serv:~/amnezia/AmneziaVPN_Linux_4.7.0.0$ chmod +x AmneziaVPN_Linux_Installer.bin
serv:~/amnezia/AmneziaVPN_Linux_4.7.0.0$ ./AmneziaVPN_Linux_Installer.bin 
./AmneziaVPN_Linux_Installer.bin: error while loading shared libraries: libxcb-xinerama.so.0: cannot open shared object file: No such file or directory
```

OS: Ubuntu 24.04.1 LTS

Please tell me what I'm doing wrong. There are no installation instructions anywhere

**Comment by L1gHtFox** [comment]
Did you fixed that? How did you installed it?

**Comment by rasolAAaa** [comment]
سلام من چنگال نصب کردم الان هیچ کار نمیکنه راهنمایی فرمایید

در تاریخ دوشنبه ۱۴ اکتبر ۲۰۲۴،‏ ۱۱:۵۵ Mark ***@***.***> نوشت:

**Comment by L1gHtFox** [comment]
> سلام من چنگال نصب کردم الان هیچ کار نمیکنه راهنمایی فرمایید

 I've tried hot same issue

**Comment by DekaBraZ** [comment]
On Ubuntu 24+ `sudo apt install libxcb-xinerama0` fixed things for me. I'm not sure if it's installer related issue or the application itself needs it.
