### ISSUE TITLE
Make reboot button more obvious

### ISSUE THREAD

**Issue by RavMda** [amnezia-vpn/amnezia-client#1121]
https://github.com/amnezia-vpn/amnezia-client/blob/d4fff4af3cf836cc021c68f35779759c9152a96f/client/core/controllers/serverController.cpp#L215

I thought this shitty button would reboot only your vpn container and not whole fucking production server
Thunderstrike your village 1000 times

**Comment by Nethius** [comment]
The button is literally called “reboot SERVER”, it's warning red and displays a confirmation window, the confirmation window says “do you really want to reboot the server?”, how much more obvious could it be?

**Comment by RavMda** [comment]
why would you put that inside a vpn app, and why there's no button to reboot vpn containers? @Nethius
