### ISSUE TITLE
app white-list split tunneling mode on desktop

### ISSUE THREAD

**Issue by EntityinArray** [amnezia-vpn/amnezia-client#1127]
**Describe the bug**
Split tunnelling only provides black-list, a list of apps that get excluded from VPN.

**To Reproduce**
1. Go to Split Tunneling on Desktop
2. Only black-list is available

**Expected behavior**
User should be able to define both black-list and white-list *at the same time*, with black-list having bigger priority than white-list

**Log files**
not needed

**Screenshots**
![image](https://github.com/user-attachments/assets/7c9a8c90-cfbe-4c5a-8d6d-346e72c0d7e0)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10 Pro
 - Version [e.g. 2.1.2] 4.8.1.9

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04] Ubuntu 23.10

**Comment by llimonix** [comment]
the same mistake
![image](https://github.com/user-attachments/assets/190c199f-0b79-419c-a8b9-cc4765e410d0)

**Comment by G7AX** [comment]
same issue on win10

**Comment by Kadirov-Artem** [comment]
I have the same issue
I'd like to add Discord to my whitelist but the only thing I can do is adding applications to the black list

**Comment by strelokhalfer** [comment]
Also, the blacklist doesn't work properly - selected apps lose access to the internet.

**Comment by EntityinArray** [comment]
> Also, the blacklist doesn't work properly - selected apps lose access to the internet.

you need to disable KillSwitch, it's a wierd feature enabled by default that kills any non-vpned connections
![image](https://github.com/user-attachments/assets/677ef62b-b65c-4ed4-9956-dc87015c7804)

**Comment by strelokhalfer** [comment]
> you need to disable KillSwitch, it's a wierd feature enabled by default that kills any non-vpned connections

Yeah, found it too, but thanks.
Still i consider this as bug.

**Comment by etozhefifan** [comment]
+1
Also don't have an option to use Amnezia for certain apps. Using linux client on arch.

**Comment by Redplcs** [comment]
+1
Funny that this feature works on mobile

**Comment by strelokhalfer** [comment]
It looks like this menu option is disabled on purpose. I switched the mode to whitelist in the registry, but then everything goes through the VPN, ignoring the list.
`HKEY_CURRENT_USER\Software\AmneziaVPN.ORG\AmneziaVPN\Conf\appsRouteMode` set to 1 for whitelist
![Screenshot 2024-10-08 213328](https://github.com/user-attachments/assets/eea44e33-525e-4138-bc1b-26f29f2f4ad2)

**Comment by hahatulk** [comment]
please add whitelist

**Comment by sx-motive** [comment]
As I understand it, there is currently no feature that allows you to add a separate application to vpn traffic. 

For those who are looking for the possibility to add Discord as a separate application, I can suggest using the section "Site-based split tunneling", and add discords cdns there like this:

![{D2418E11-2505-4EAF-82BA-22427251CDD9}](https://github.com/user-attachments/assets/fb164b41-6258-4350-8124-571366073733)

make sure you have right mode, before connect:

![{1527E784-E63E-4615-98BC-DA2F0445AFCD}](https://github.com/user-attachments/assets/47d46917-c228-452a-93e4-460062773efe)

this will make your discord desktop app works through vpn.

**Comment by hahatulk** [comment]
> As I understand it, there is currently no feature that allows you to add a separate application to vpn traffic.
> 
> For those who are looking for the possibility to add Discord as a separate application, I can suggest using the section "Site-based split tunneling", and add discords cdns there like this:
> 
> ![{D2418E11-2505-4EAF-82BA-22427251CDD9}](https://private-user-images.githubusercontent.com/54843147/374684549-fb164b41-6258-4350-8124-571366073733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTMzNzAsIm5iZiI6MTcyODQxMzA3MCwicGF0aCI6Ii81NDg0MzE0Ny8zNzQ2ODQ1NDktZmIxNjRiNDEtNjI1OC00MzUwLTgxMjQtNTcxMzY2MDczNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE4NDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MjYwMzYxOWEwZWQ3YzNiMTljZjVjMjQ0MGY1M2YzOTdlMTA1OTNhZWVjOWU5NjZkNGZjOGI2NzQxNjk3NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Z_Plgfrfoi3xwZyAJgo4E4AqgyGTe592I9Oj3qvLC8)
> 
> make sure you have right mode, before connect:
> 
> ![{1527E784-E63E-4615-98BC-DA2F0445AFCD}](https://private-user-images.githubusercontent.com/54843147/374685044-47d46917-c228-452a-93e4-460062773efe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTMzNzAsIm5iZiI6MTcyODQxMzA3MCwicGF0aCI6Ii81NDg0MzE0Ny8zNzQ2ODUwNDQtNDdkNDY5MTctYzIyOC00NTJhLTkzZTQtNDYwMDYyNzczZWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE4NDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNGQ4N2RiNmZjMjI4OGJhOTFjMmQyNjAzNzgxZWY3NjQ3ZTUwYTU1NDdmNmVlMTNlZDM5YTQzZTU0ZThmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w32mpZg82IfqVemmXZE_jN8k-tG6cFBZtzZZ0OtGnXU)
> 
> this will make your discord desktop app works through vpn.

works, but RTC still broken, cant be fixed with current tunneling

**Comment by Redplcs** [comment]
> > As I understand it, there is currently no feature that allows you to add a separate application to vpn traffic.
> > For those who are looking for the possibility to add Discord as a separate application, I can suggest using the section "Site-based split tunneling", and add discords cdns there like this:
> > ![{D2418E11-2505-4EAF-82BA-22427251CDD9}](https://private-user-images.githubusercontent.com/54843147/374684549-fb164b41-6258-4350-8124-571366073733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTMzNzAsIm5iZiI6MTcyODQxMzA3MCwicGF0aCI6Ii81NDg0MzE0Ny8zNzQ2ODQ1NDktZmIxNjRiNDEtNjI1OC00MzUwLTgxMjQtNTcxMzY2MDczNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE4NDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MjYwMzYxOWEwZWQ3YzNiMTljZjVjMjQ0MGY1M2YzOTdlMTA1OTNhZWVjOWU5NjZkNGZjOGI2NzQxNjk3NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Z_Plgfrfoi3xwZyAJgo4E4AqgyGTe592I9Oj3qvLC8)
> > make sure you have right mode, before connect:
> > ![{1527E784-E63E-4615-98BC-DA2F0445AFCD}](https://private-user-images.githubusercontent.com/54843147/374685044-47d46917-c228-452a-93e4-460062773efe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTMzNzAsIm5iZiI6MTcyODQxMzA3MCwicGF0aCI6Ii81NDg0MzE0Ny8zNzQ2ODUwNDQtNDdkNDY5MTctYzIyOC00NTJhLTkzZTQtNDYwMDYyNzczZWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE4NDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNGQ4N2RiNmZjMjI4OGJhOTFjMmQyNjAzNzgxZWY3NjQ3ZTUwYTU1NDdmNmVlMTNlZDM5YTQzZTU0ZThmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w32mpZg82IfqVemmXZE_jN8k-tG6cFBZtzZZ0OtGnXU)
> > this will make your discord desktop app works through vpn.
> 
> works, but RTC still broken, cant be fixed with current tunneling

Try those:
discord-attachments-uploads-prd.storage.googleapis.com 
dis.gd 
discord.co 
discord.com 
discord.design 
discord.dev 
discord.gg 
discord.gift 
discord.gifts 
discord.media 
discord.new 
discord.store 
discord.tools 
discordapp.com 
discordapp.net 
discordmerch.com 
discordpartygames.com 
discord-activities.com 
discordactivities.com 
discordsays.com

Got them from random post about reviving discord using GoodbyeDPI. I not guarantee that this would work

**Comment by EntityinArray** [comment]
> As I understand it, there is currently no feature that allows you to add a separate application to vpn traffic.
> 
> For those who are looking for the possibility to add Discord as a separate application, I can suggest using the section "Site-based split tunneling", and add discords cdns there like this:
> 
> ![{D2418E11-2505-4EAF-82BA-22427251CDD9}](https://private-user-images.githubusercontent.com/54843147/374684549-fb164b41-6258-4350-8124-571366073733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTQ1NzIsIm5iZiI6MTcyODQxNDI3MiwicGF0aCI6Ii81NDg0MzE0Ny8zNzQ2ODQ1NDktZmIxNjRiNDEtNjI1OC00MzUwLTgxMjQtNTcxMzY2MDczNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE5MDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNTM5MDBhZjFhZjA1OThkNjk2YzZlNjVjZDZkMDM3MDI2OGZlNmIzZTVmOWMyMDRmNTE0OWVjMmM5NWE3MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0fzaXFt_dBtWChmDHq877lENN8UNzWrb-8OxbrGQMsU)
> 
> make sure you have right mode, before connect:
> 
> ![{1527E784-E63E-4615-98BC-DA2F0445AFCD}](https://private-user-images.githubusercontent.com/54843147/374685044-47d46917-c228-452a-93e4-460062773efe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTQ1NzIsIm5iZiI6MTcyODQxNDI3MiwicGF0aCI6Ii81NDg0MzE0Ny8zNzQ2ODUwNDQtNDdkNDY5MTctYzIyOC00NTJhLTkzZTQtNDYwMDYyNzczZWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE5MDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOGZlMTRhYzkxZTJkNmIzZjRmNGJmMjBiMjI2NzZjNzhkODAyOTUzN2FmZjFkMjI4YWRkMWNlNWM2MTNjZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qIZ52QuyN2hvsoZvNvvADagQfOUb7_qd1TJyq-pYDA0)
> 
> this will make your discord desktop app works through vpn.

i use amneziawg and it won't let me do that @sx-motive 
![image](https://github.com/user-attachments/assets/0f4b412b-27e8-405b-a6a9-6477569903ff)

**Comment by b5414** [comment]
Official response about this (_changing to 1 by regedit_):

> This setting is not intended and will not work for Windows

**Comment by Nethius** [comment]
Whitelists for apps is implemented only on android, due to the peculiarities of implementation on windows this mode is not available

**Comment by EntityinArray** [comment]
For anyone who seeks to make Discord/other specific apps work without forwarding their entire traffic through VPN, I found a suitable app.
https://github.com/wiresock/WireSockUI

![image](https://github.com/user-attachments/assets/348ce93f-0d4d-4c33-936e-c503fe1ee2c4)
![image](https://github.com/user-attachments/assets/ca5d48d5-b485-4caf-88fb-9cffc0cf2204)
![image](https://github.com/user-attachments/assets/4f8180db-67e9-4929-b8ed-65c4550ee012)
![image](https://github.com/user-attachments/assets/882d7047-131d-4969-9888-62e234ea4767)

**Comment by brnor** [comment]
> For anyone who seeks to make Discord/other specific apps work without forwarding their entire traffic through VPN, I found a suitable app. https://github.com/wiresock/WireSockUI

How exactly is this supposed to work if Amnezia's configs are full of properties that only their implementation uses?

**Comment by EntityinArray** [comment]
> > For anyone who seeks to make Discord/other specific apps work without forwarding their entire traffic through VPN, I found a suitable app. https://github.com/wiresock/WireSockUI
> 
> How exactly is this supposed to work if Amnezia's configs are full of properties that only their implementation uses?

i ditched amnezia configs and made regular wireguard configs

**Comment by BlogPlayCode** [comment]
> i ditched amnezia configs and made regular wireguard configs

How can I make my Amnezia's configs to be regular wireguard configs?

**Comment by DmitriyFrogo** [comment]
@brnor @BlogPlayCode 
> How exactly is this supposed to work if Amnezia's configs are full of properties that only their implementation uses?

> How can I make my Amnezia's configs to be regular wireguard configs?


If your ISP blocks WG connections and it only works with Amnezia, try WireSock + WireSockUI + this method:
https://gist.github.com/httpsx/76a98ea28e6f3a4ffc947e768c0b6c01

(If you need to split tunnel. If not - you can use any wireguard client)

**Comment by drizzle-mizzle** [comment]
Are there any plans to make whilte-list thing work at all, at least in near future?

**Comment by kindapath** [comment]
> @brnor @BlogPlayCode
> 
> > How exactly is this supposed to work if Amnezia's configs are full of properties that only their implementation uses?
> 
> > How can I make my Amnezia's configs to be regular wireguard configs?
> 
> If your ISP blocks WG connections and it only works with Amnezia, try WireSock + WireSockUI + this method: https://gist.github.com/httpsx/76a98ea28e6f3a4ffc947e768c0b6c01
> 
> (If you need to split tunnel. If not - you can use any wireguard client)

thank you, i used this and it works

**Comment by Vitzek** [comment]
> Try those: discord-attachments-uploads-prd.storage.googleapis.com dis.gd discord.co discord.com discord.design discord.dev discord.gg discord.gift discord.gifts discord.media discord.new discord.store discord.tools discordapp.com discordapp.net discordmerch.com discordpartygames.com discord-activities.com discordactivities.com discordsays.com
> 
> Got them from random post about reviving discord using GoodbyeDPI. I not guarantee that this would work

Also add 
media.discordapp.net
