### ISSUE TITLE
Поддержка Дискорда

### ISSUE THREAD

**Issue by G1ZMO** [amnezia-vpn/amnezia-client#1128]
Подскажите, будет ли осуществлена поддержка десктоп версии дискорда для подсоединения к голосовым каналам в бесплатной версии?

**Comment by Timtaran** [comment]
не поверишь, но все итак работает

**Comment by b5414** [comment]
https://github.com/ImMALWARE/bash-warp-generator/tree/main

**Comment by Azinuss** [comment]
https://github.com/iamkuper/amnezia-discord-config

**Comment by amnzam** [comment]
Здравствуйте. Мы добавили поддержку Дискорда в Amnezia Free. Конфиг можно получить через последнюю версию клиента. Клиенты уже доступы в App Store и Google Play.
