### ISSUE TITLE
separate traffic tunneling in the Windows client does not work.

### ISSUE THREAD

**Issue by saintedlittle** [amnezia-vpn/amnezia-client#1131]
Good afternoon, the problem is that on Windows 10 and Windows 11, when trying to enable separate tunneling, it is not possible to switch the type: Whether applications from the list should be tunneled or not. I tried different ways, nothing helped. It just won't let you change it.

![image](https://github.com/user-attachments/assets/6a9cd488-44c6-4d92-a3c6-12299c841d48)

**Comment by b5414** [comment]
1. `Win+R` 
2. `regedit` 
3. `HKEY_CURRENT_USER\SOFTWARE\AmneziaVPN.ORG\AmneziaVPN\Conf`
4. Set `appsRouteMode` to `1`




---


Official response about this:

> This setting is not intended and will not work for Windows


@ https://t.me/amnezia_vpn_en/10866

**Comment by b5414** [comment]
Btw, this tunneling not working for Cloudflare WARP, even on the beta version

**Comment by Redplcs** [comment]
https://github.com/amnezia-vpn/amnezia-client/issues/1127

**Comment by Nethius** [comment]
Whitelists for apps is implemented only on android, due to the peculiarities of implementation on windows this mode is not available
