### ISSUE TITLE
Client hangs and crashes on boot when there are too many sites in the Split tunneling site list

### ISSUE THREAD

**Issue by pixelqiwi** [amnezia-vpn/amnezia-client#1135]
You would think that uninstalling the app and wiping its traces in appdata would be enough, but sadly after a reinstall it still remembers its configuration, which is unfortunate for me because apparently there is such thing as "too many Split Tunneling sites in the list", which makes the client crash on boot. 

System is Windows 11 23H2.
The site list I imported into the client is attached to this post. 
[amnezia_sites.json](https://github.com/user-attachments/files/17301071/amnezia_sites.json)

**Comment by pixelqiwi** [comment]
update: deleting every mention of AmneziaVPN in the Windows registry seemed to help me factory reset the app settings, but the core issue is still present: app hangs if you have too many sites in the site list.

**Comment by 2048khz-gachi-rmx** [comment]
Works for me, no crashes
Opening the list lags and leaks memory like a motherfucker, but the client boots and works just fine
[rknligmaballs.json](https://github.com/user-attachments/files/17305262/rkntonguemyanus.json)

<details>
<summary>demo</summary>
cat for stutter reference
<video src="https://github.com/user-attachments/assets/22316c49-6ee7-49db-934b-7da4412251f4"/>
</details>

**Comment by pixelqiwi** [comment]
> Works for me, no crashes Opening the list lags and leaks memory like a motherfucker, but the client boots and works just fine [rknligmaballs.json](https://github.com/user-attachments/files/17305262/rkntonguemyanus.json)
> 
> demo
> cat for stutter reference
>  nomacs_SvA8lHiedH.mp4

cheers, yoinked necessary lines from your file for myself, and it works surprisingly well, i guess i screwed up with my list file somewhere then... /shrug

**Comment by Rebel028** [comment]
Having the same issue here. 
My guess is something's not right with json deserialization.
What's the point of having json list of sites anyway? TXT should work fine
