### ISSUE TITLE
Split tunneling on PC, discord

### ISSUE THREAD

**Issue by Monstass** [amnezia-vpn/amnezia-client#1152]
According to [this](https://habr.com/ru/companies/amnezia/articles/850012/) article, u guys are saying that "Split tunneling will be available for all Premium service users by Monday, and anyone who wants to will be able to add Discord subnets to the split tunneling of Premium configurations."

Sounds good, and if i understand it correctly, split tunneling on PC client should work like **whitelist**. But still u closed #1127 issue because 'it should not working on windows like a whitelist, but blacklist'.

Simple questions: why? And have I misunderstood something? 

Many thanks.

**Comment by Nethius** [comment]
Amnezia has 2 types of tunneling, site split tunneling and app split tunneling. #1127 about app split tunneling
