### ISSUE TITLE
App-based split tunneling can only exclude applications, but cannot include them in the list of vpn-using applications

### ISSUE THREAD

**Issue by PandaYaY** [amnezia-vpn/amnezia-client#1168]
When I tried to add applications that should use a vpn, I found that I could not make this list use a vpn, instead of excluding these applications from using a vpn.
Platform: windows
Version: 4.7.0.0
![1](https://github.com/user-attachments/assets/225595fa-f211-486a-906c-fc0a385bba41)

**Comment by Nethius** [comment]
Whitelists for apps is implemented only on android, due to the peculiarities of implementation on windows this mode is not available

**Comment by DearFox** [comment]
> Whitelists for apps is implemented only on android, due to the peculiarities of implementation on windows this mode is not available

But TunnlTo can do this, so technically it is possible.

**Comment by ilyachase** [comment]
@Nethius @outspace hi folks, since you were the ones implementing app-based split tunneling for android, could you possibly elaborate what are the blockers to do the same for Windows?

**Comment by ilyachase** [comment]
@albexk pinging you as well, would be awesome to have more details on this one :pray:
