### ISSUE TITLE
Amnezia free изображения в Дискорде не отправляются

### ISSUE THREAD

**Issue by Verity-Freedom** [amnezia-vpn/amnezia-client#1169]
Если отправить изображение в Дискорде кому угодно то оно не отправится и встанет на вечную обработку.
![image](https://github.com/user-attachments/assets/21b7d708-1a42-4f1c-a032-12a4ee2e583f)

**Comment by Nethius** [comment]
https://t.me/amneziavpn_ru_channel_group
