### ISSUE TITLE
amnezia wg stopped actually working

### ISSUE THREAD

**Issue by klazustrem** [amnezia-vpn/amnezia-client#1170]
i downloaded this vpn like few weeks ago, it was working nicely, but starting from yesterday when im connecting to vpn all web pages and etc not loading at all 
the first two img shows that i have no issues while vpn disabled
<img width="793" alt="image" src="https://github.com/user-attachments/assets/25dfade4-b224-4a23-8642-9f433e2d4f39">

and this 2 shows that i cant load even google page 
<img width="790" alt="image" src="https://github.com/user-attachments/assets/436cd356-1c71-4750-b1e4-86342ff1acc2">
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/12db70d4-fe82-4c81-af48-4a59a86f46b5">
i dunno what to do with this, no info on github found

**Comment by klazustrem** [comment]
and i also tried amnezia vpn instead of amnezia wg, not connecting at all

**Comment by klazustrem** [comment]
in amnezia vpn the issue is i press connect button it lights up for a second with "connecting" and gets back to "connect" without any possibility to connect

**Comment by Minnonar** [comment]
Смотри, у меня сложилась такая же ситуация как у тебя. 2 раза. В первый раз, причиной послужил антивирусник, а точнее dr. web. Просто отключил его на время. Сегодня, буквально час назад тоже самое. В этот раз я просто создал новый аккаунт GitHub, и скачал просто новый Warp. Ну ещё на всякий переустановил Amnezia

**Comment by Nethius** [comment]
you should ask the person you got your config from to connect, it has nothing to do with the app

**Comment by klazustrem** [comment]
> Смотри, у меня сложилась такая же ситуация как у тебя. 2 раза. В первый раз, причиной послужил антивирусник, а точнее dr. web. Просто отключил его на время. Сегодня, буквально час назад тоже самое. В этот раз я просто создал новый аккаунт GitHub, и скачал просто новый Warp. Ну ещё на всякий переустановил Amnezia

ща попробую и скажу помогло ли

**Comment by klazustrem** [comment]
alr i fixed it by just reinstalling WARP config and Amnezia, maybe it will help somebody
