### ISSUE TITLE
Amnezia does not install on ubuntu 24.04.01 LTS

### ISSUE THREAD

**Issue by Molp1o** [amnezia-vpn/amnezia-client#1184]
When i try to run bin file in console:
![image](https://github.com/user-attachments/assets/4bcea776-7a8a-44b7-aea3-296bc8efb63e)

If i try to run bin file in file explorer nothing happens

What to do?

**Comment by AKotov-dev** [comment]
@Molp1o 
Last Release: [AmneziaVPN 4.8.1.9](https://github.com/amnezia-vpn/amnezia-client/releases)

You need to launch it either with the mouse or like this (add `slash`): `./AmneziaVPN_Linux_Installer.bin`

In addition, to run the already installed program normally, you need to install the following packages:
For deb-based (Debian/Ubuntu/Mint/etc...)
```
sudo apt install libxcb-cursor0
```
For rpm-based (RedHat/Fedora/Mageia/etc...)
```
dnf install lib64xcb-util-cursor0
```
...or something similar, depending on the distribution.

![raccoon_youtube](https://github.com/user-attachments/assets/1a8a4a0a-040e-42a8-8bbd-6041c9a29b47)

Also, if the connection does not occur, try disabling `KillSwitch` (`Settings-Connection-KillSwitch`).

**Comment by Molp1o** [comment]
Thank you for your help! I've installed libxcb-cursor0 and it worked!

**Comment by AKotov-dev** [comment]
@Molp1o 
Ок.. Похоже, здесь можно общаться на русском языке...  Проект наши парни пилят.. Простите... Хотя, проект вроде бы международный. А ладно... Опять ничего не понятно, самообслуживание.. ))

**Comment by Gelassen** [comment]
@AKotov-dev , I have the issue to install linux client out-of-the-box without solving issues with missed dependencies. There are many of them which gives me a clue I am might doing something wrong. 
```
Environment: Ubuntu 24.04
Client: AmneziaVPN 4.8.2.3
```

Steps to reproduce:
1. Download the latest client
2. Extract zip and tar archives
3. $ chmod +x  sudo chmod +x AmneziaVPN_Linux_Installer.bin
4. ./AmneziaVPN_Linux_Installer.bin

Observed behavior: 
```
./AmneziaVPN_Linux_Installer.bin: error while loading shared libraries: libxcb-xinerama.so.0: cannot open shared object file: No such file or directory
```
and many similar others missed dependencies after resolving the previous one

**Comment by PrimeRise** [comment]
Простите, но вам следовало бы почитать доки, где белым по черному написано как нужно устанавливать приложение:
Ubuntu 24.04.1 (x64)
для установки AmneziaVPN, помимо административных прав пользователя, нужны:

sudo apt install libxcb-xinerama0
без этого, не запускается GUI установщика

sudo apt install libxcb-cursor0
без этого, не запускается GUI AmneziaVPN, если используется Xorg вместо Wayland, (или если выполнить sudo AmneziaVPN)

**Comment by kost-1** [comment]
Мне для запуска потребовались ещё 2 строчки:

apt install libxcb-icccm4
apt install libxcb-keysyms1

Свежеустановленная Xubuntu 24.04.2 LTS
