### ISSUE TITLE
server error:docker container missing

### ISSUE THREAD

**Issue by bullhead1375** [amnezia-vpn/amnezia-client#119]
when trying to configure a manual server,this happens in all protocols ,even the docker and docker.io is installed on the server
![Screenshot 2022-10-18 235413](https://user-images.githubusercontent.com/45820966/196537216-767b6540-0194-4d8d-8f1c-c4d791834325.png)

**Comment by Nethius** [comment]
Hi @bullhead1375 It looks like you are connecting to the server with a user who is prompted for a password for sudo . For successful configuration, you need to connect as root or a user who does not have a password for sudo

**Comment by sercit** [comment]
Unfortunately got this message on the root too

**Comment by pokamest** [comment]
Please check latest release 3.1.0
https://github.com/amnezia-vpn/amnezia-client/releases/tag/3.1.0

**Comment by Llahainur** [comment]
I Had the same error running on server as root user, version 4.4.0.0 desktop, server is Ubuntu 20.04

**Comment by SokolovSV** [comment]
I Had the same error running on server as root user, version AmneziaVPN_4.5.3.0_x64, server is Debian 11.9
