### ISSUE TITLE
ErrorCode: 1100 ошибка при получении конфигурации из API.

### ISSUE THREAD

**Issue by n4khnarn** [amnezia-vpn/amnezia-client#1206]
Здравствуйте, имею премиум доступ, но вчера на телефоне и ТВ перестало подключать пишет такую ошибку, а на ПК все норм, что нужно сделать?
кеш все чистил переустанавливал программу и т.д.😕
![Screenshot_2024-10-26-14-24-05-816_org amnezia vpn](https://github.com/user-attachments/assets/dfdfe728-1b42-427e-9a65-489d7b51a25d)

**Comment by Nethius** [comment]
https://t.me/amnezia_premium_support_bot
