### ISSUE TITLE
Amnezia not work to Linux Mint

### ISSUE THREAD

**Issue by trofim373** [amnezia-vpn/amnezia-client#1216]
**Describe the bug**
The application is installed from the bin file, but does not start. When launched through the terminal, it gives an error:
AmneziaVPN
sh: 0: getcwd() failed: No such file or directory
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/opt/AmneziaVPN/client/plugins//platforms:" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, wayland, minimalegl, wayland-egl, offscreen, eglfs, linuxfb, xcb.

Aborted (core dumped)

**System**
Linux Mint 22 Cinnamon 6.2.9, Linux kernel 6.8.0-47-generic

**Comment by aketawi** [comment]
have you tried following this? Looks similar to your issue.

https://docs.amnezia.org/troubleshooting/not-running-on-linux

**Comment by trofim373** [comment]
> have you tried following this? Looks similar to your issue.
> 
> https://docs.amnezia.org/troubleshooting/not-running-on-linux

thanks, this command helped to solve the problem: sudo apt install libxcb-xinerama0 libxcb-cursor0
