### ISSUE TITLE
Not possible to enter SSH key in Windows client

### ISSUE THREAD

**Issue by EugZol** [amnezia-vpn/amnezia-client#122]
Steps:

* Settings -> Server -> + -> Connect using SSH key
* Paste SSH key

Expected result: key is pasted correctly

Actual result: line breaks are deleted, key is pasted as single line. Changing `\n` to `\r\n` doesn't change anything.

Later this results in "SSH key error" for any installation attempts.

**Comment by dmiwell** [comment]
Looks like the same as https://github.com/amnezia-vpn/desktop-client/issues/75

**Comment by dusk-comes** [comment]
The same bug for Linux client also. Your target base is housekeeper, isn't your?

**Comment by pokamest** [comment]
Please check latest builds with fixes:
https://github.com/amnezia-vpn/amnezia-client/actions/runs/5847886029
