### ISSUE TITLE
Users list don't showing on MacOS with XRAY protocol

### ISSUE THREAD

**Issue by utmaks** [amnezia-vpn/amnezia-client#1236]
**Describe the bug**
When I generate new users for AmneziaWG protocol – I can view list of users and revoke profiles. But for Xray protocol last version (pre-release 2 weeks ago) of Mac OS application for ARM chips – don’t show me user list. 

**To Reproduce**
1. Deploy server with Xray protocol
2. Add new user and generate profile
3. Go to screen with users list for each server
4. See empty user list

**Expected behavior**
A full user list like AmneziaWG protocol.

**Screenshots**

<img width="242" alt="Screenshot 2024-11-06 at 19 23 06" src="https://github.com/user-attachments/assets/9c76aa70-22b3-4371-8723-df6b67cececd">

**Desktop (please complete the following information):**
 - OS: MacOS 15.0 (same error for previous OS\)
 - Version (i can't copy):
<img width="305" alt="Screenshot 2024-11-06 at 19 51 07" src="https://github.com/user-attachments/assets/8f29e2e3-6059-49bb-9e93-80edb8f98453">

**Server (please complete the following information):**
 - OS: Ubuntu 24.04 and 22.04

**Comment by the-aLeXiS** [comment]
@Nethius Same behaviour on Windows and Android (versions tested 4.8.1.9 and 4.8.2.3)

**Comment by nxstd** [comment]
AFAIK, XRay in AmneziaVPN uses one key for all users. So the user list is always empty, no matter what platform you use AmneziaVPN on.
