### ISSUE TITLE
Restore access to admin

### ISSUE THREAD

**Issue by ultraleks** [amnezia-vpn/amnezia-client#1259]
I was lost my device, where i setted up self-hostd Amnezia VPN. How i can restore settings to another device to control all users on server?
I tryed add server on other device in app Amnezia, but is started to install server. Is this action - setting up new instances of Amnezia? If i did it - i will lost all already configured users?

**Comment by virussell** [comment]
The only way is to reinstall Amnezia on the server. Yes, this will cause other users to lose their settings, they will need to be issued new keys.

**Comment by Nethius** [comment]
> The only way is to reinstall Amnezia on the server. Yes, this will cause other users to lose their settings, they will need to be issued new keys.

this is not true, you can use the “skip setup” option and then click “Check the server for previously installed Amnezia services” in the server settings

**Comment by AtaarSatag** [comment]
> > The only way is to reinstall Amnezia on the server. Yes, this will cause other users to lose their settings, they will need to be issued new keys.
> 
> this is not true, you can use the “skip setup” option and then click “Check the server for previously installed Amnezia services” in the server settings

OR you can go to Share VPN Access > ⋮ menu > Share > choose a server > Share button, then copy a key and add it as a regular VPN.
