### ISSUE TITLE
Google services bypasses AmnesiaVPN

### ISSUE THREAD

**Issue by QuMix64** [amnezia-vpn/amnezia-client#1265]
Hello, I bought an Amnesia VPN server today (Netherlands) which works perfectly. However, there is one big problem related to google. For some unknown reason, only google detects my original location while all other sites do not. I've checked on many “Determine my IP" sites, but all of them show the IP used in AmnesiaVPN. I even tried changing the server's IP, but nothing changed. Somebody help me, please

**Comment by terroristkanomerodin** [comment]
Hello! How did you resolve the issue?

**Comment by StrikerRUS** [comment]
Google is quite difficult to fool. You need a residential IP/proxy to do this.

Ref:
- https://4pda.to/forum/index.php?showtopic=137860&st=20760#entry129307422
- https://4pda.to/forum/index.php?showtopic=137860&st=21240#entry130212791
