### ISSUE TITLE
critical Critical, trying to add invalid route: 1.1.1.1

### ISSUE THREAD

**Issue by SBKubric** [amnezia-vpn/amnezia-client#143]
Hi, encountered a problem using the client for Linux.

# Expected behavior
On pressing button "Connect" connection is established.

# Actual behavior.
On pressing button "Connect" client **says**, that connection is established. 
![image](https://user-images.githubusercontent.com/5788811/209177712-83739a2d-058d-4c86-bfa4-facf805a70dd.png)

However, the logs shows that actually no wireguard connection was established. 

Instead, an error occured:

```
2022-12-22 18:54:38 debug IpcServerProcess started,  "/usr/bin/wg" ("--add", "/tmp/AmneziaVPN.WireGuard0.conf")
2022-12-22 18:54:39 debug Flush dns completed
2022-12-22 18:54:39 critical Critical, trying to add invalid route:  1.1.1.1 
2022-12-22 18:54:39 critical Critical, trying to add invalid route:  1.1.1.1
```

Here is /tmp/AmneziaVPN.WireGuard0.conf:
```
[Interface]
Address = 10.8.1.2/32
DNS = 1.1.1.1, 1.0.0.1
PrivateKey = <privatekey_intf>

[Peer]
PublicKey = <publickey_peer>
PresharedKey = <preshared_key>
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 167.172.191.74:51820
PersistentKeepalive = 25

```

Temporal workaround is to create a connection manually with **wg-quick**, slightly inconvenient, but better, than nothing :-)

**Comment by pokamest** [comment]
Fixed in latest 4.x releases
