### ISSUE TITLE
AmneziaVPN ignores $PATH env variable

### ISSUE THREAD

**Issue by naughtyfox** [amnezia-vpn/amnezia-client#147]
I tried to connect to OpenVPN over cloak server and got the following error:
```
2023-01-09 12:52:52 critical VpnProtocol error, code ErrorCode::26(Cloak (ck-client) executable missing) Cloak (ck-client) executable missing
```

Then I downloaded it from github: https://github.com/cbeuw/Cloak/releases/tag/v2.6.0 and copied the executable `ck-client` to `/usr/local/bin` which corresponds to my `$PATH`. Tested if it works:
```
$ which ck-client 
/usr/local/bin/ck-client
```

I `strace`d the app and figured out it looks only to:
```
$ grep ck-client amnezia.strace 
120706 access("/usr/sbin/ck-client", F_OK) = -1 ENOENT (No such file or directory)
120706 access("/usr/bin/ck-client", F_OK) = -1 ENOENT (No such file or directory)
```

I believe the app should use `$PATH`.

Thanks.

**Comment by pokamest** [comment]
Cloak plugin bundled in latest 4.x releases, issue fixed
