### ISSUE TITLE
[Request] Wireguard+Wstunnel & Wireguard+Cloak

### ISSUE THREAD

**Issue by emzziper** [amnezia-vpn/amnezia-client#182]
If you add these 2 to the application, they will be really useful.

**Comment by emzziper** [comment]
Hello again. I am using both wstunnel and cloak with Wireguard. Wireguard is blocked in my country, so the only way I can use Wireguard is wstunnel or Cloak and it works very well, but since it takes time to set up, it would be great if it was added in amnezia.

**Comment by vincent1890** [comment]
Wstunnel (wss) + Wireguard which is the perfect combo but if we could have this integrate into the application this would be really top
[https://github.com/erebe/wstunnel/issues/292](https://github.com/erebe/wstunnel/issues/292)

Currently :
[(Windows/Linux) App_(file/chrome/other) -> Wireguard (UDP 51820) -> (IN - UDP 51820 )Wstunnel(Out - TCP 443) -> Internet World -> (In - TCP 443)Docker-RevProxy(Out - TCP 9442) -> (In - TCP 9442)Docker-WsTunnel(Out - UDP 51820) -> (In UDP 51820)_Wireguard-Server-VPN -> (Enterprise)Private-Lan] this works well
