### ISSUE TITLE
Error occurred while configuring server, failed to start remote process on server [Ubuntu 20.04]

### ISSUE THREAD

**Issue by skygunner** [amnezia-vpn/amnezia-client#215]
Tried to install the server using the client, when there's no docker engine installed on the server, it seems to fail to install the docker engine or start it. 
So I manually installed docker engine and added current user to docker group.
Tried again to config the server, this time can see it is trying to start containers in top, but evetually it failed with the titled error and no container is running after the process. 
Is there any log I can check to see what is wrong during the process?

The vm is not fresh so there must be some conflicts with the software. 

In the syslog I can see some failed audit but the cmd is entirely not readable.

**Comment by HisenZhang** [comment]
I encountered the same error and got it fixed by restarting the server.

**Comment by pokamest** [comment]
Please check latest releases
https://github.com/amnezia-vpn/amnezia-client/actions/runs/5847886029
