### ISSUE TITLE
Ssh protocol error (Ed25519)

### ISSUE THREAD

**Issue by ikyquocked** [amnezia-vpn/amnezia-client#218]
Hi, I just bought a 1984 hosting and tried to install AmneziaVPN and got a bug. 

Login+password auth. After pressing “start configuring” button the error occuring **“Error occured while configuring server. Ssh protocol error.”**
After some troubleshooting a found the reason in terminal:
```
Ssh error: 3 "SSH Protocol error: Server and client HostKey capabilities don't match.\nClient list: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss\nServer list: ssh-ed25519
ServerController::runScript connectToHost error:  10
Setup server finished with code ErrorCode::10("Ssh protocol error")
```
Then I was reading a lot of stuff in google and eventually checked the server ssh config /etc/ssh/sshd_config and there was 

```
#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
```
I uncomment ecdsa key and error disappeeared.

It looks like the apps (macos, android) dont support Ed25519. 

Maybe my case is unique but it was not obviously how to solve it. I think it could be very useful to add this Ed25519 auth method to the app to exclude this error for future Amnezia users (not linux admins)).

Ubuntu server 20.04
clients Macos 10.14 and Android 10

**Comment by pokamest** [comment]
Hi!
What is AmneziaVPN version you using?
We are working on new 3.x release with libssh support, it should solve issues with ssh keys

**Comment by ikyquocked** [comment]
Hello @pokamest
I am using the latest releases for MacOS 2.1.2.3 and Android 2.1.2.1.
Good news from you! Im waiting for a new release!)

**Comment by pokamest** [comment]
Please check if issue fixed in latest releases
https://github.com/amnezia-vpn/amnezia-client/actions/runs/5847886029

**Comment by pokamest** [comment]
Ed25519 support implemented starting 3.x releases
