### ISSUE TITLE
Exceptions don't work

### ISSUE THREAD

**Issue by ikyquocked** [amnezia-vpn/amnezia-client#220]
Hi, while using Amnezia couple of days I added some exceptions sites to the app and noticed they are ignoring. For example, there is myip.com in the list and still I see my vpn IP when visiting, but I need my real IP. 
MacOS 10.14, app 2.1.2.3
DNS on the server
Openvpn over shadowsocks

**Comment by pokamest** [comment]
Currently, exceptions in Amnezia work in a straightforward way. When you add myip.com to the exception list, Amnezia simply resolves the IP address of myip.com and uses it for the exception. We plan to implement a DNS proxy in Amnezia which will resolve DNS names and control routing on-the-fly.

**Comment by pokamest** [comment]
Please check latest builds fix fixes - https://github.com/amnezia-vpn/amnezia-client/actions/runs/5847886029

**Comment by pokamest** [comment]
Fixed in https://github.com/amnezia-vpn/amnezia-client/releases/tag/4.1.0.1
