### ISSUE TITLE
 AmneziaVPN Client

### ISSUE THREAD

**Issue by mortag** [amnezia-vpn/amnezia-client#257]
Hi,

Is it possible the AmneziaVPN_2.1.2_Linux_Installer  only work as client?
I  installed openvpn and cloak on the server and  i  just want any client connected to server.

**Comment by mortag** [comment]
How could I generate an Amnezia VPN config file for import to AmneziaVPN Client?
Thank You

**Comment by pokamest** [comment]
Please ask for support in the Telegram support group - https://t.me/amnezia_vpn_en
