### ISSUE TITLE
Linux artifact missing?

### ISSUE THREAD

**Issue by eleius** [amnezia-vpn/amnezia-client#262]
It seems the 3.0.8 release is missing a linux artifact.

**Comment by SniperJoe** [comment]
+1. Of course there's always an option to build it from from source, but every time I hear "you're a Linux user, build it from source" I feel us straying further from ~~God~~ user friendly Linux. Also, building Amnezia requires Qt, but Qt have banned themselves in Russia, so if you a Russian Linux user, you have to have another VPN to build AmneziaVPN. mihalkov_ironic.jpg

**Comment by SniperJoe** [comment]
@eleius as a temporary solution you can download it from Actions:
https://github.com/amnezia-vpn/amnezia-client/actions/runs/5675099802

**Comment by im7mortal** [comment]
Linux support is not priority here. At least I got such response from telegram.
I had some installations problems and I have QubesOS. So I tested different Linux distros to resolve my problem. Here is how I could run it.

### :heavy_check_mark: Fedora release 36 (Thirty Six)
> sudo dnf install libssh
> ./AmneziaVPN_Linux_Installer

### :heavy_check_mark: Ubuntu 22.04.2 LTS
> ./AmneziaVPN_Linux_Installer
> AmneziaVPN
> export QT_DEBUG_PLUGINS=1
> AmneziaVPN
> sudo apt-get update && sudo apt install libxcb-xinerama0-dev
> AmneziaVPN
> export QT_DEBUG_PLUGINS=0
> AmneziaVPN
> sudo apt-get install libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev
> AmneziaVPN
> export QT_QPA_PLATFORM=wayland
> AmneziaVPN
> export QT_QPA_PLATFORM=minimal
> AmneziaVPN
> export QT_QPA_PLATFORM=minimalegl
> AmneziaVPN
> export QT_QPA_PLATFORM=linuxfb
> AmneziaVPN
> export QT_QPA_PLATFORM=wayland-egl
> AmneziaVPN
> export QT_QPA_PLATFORM=eglfs
> AmneziaVPN
> sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
> AmneziaVPN
> export QT_QPA_PLATFORM=xcb
> AmneziaVPN

### :x:Ubuntu 20.04.6 LTS
AmneziaVPN is compiled for Ubuntu 22
> ./AmneziaVPN_Linux_Installer
> AmneziaVPN
> sudo apt-get update
> apt-get install libc-bin=2.35-0ubuntu3 libc6=2.35-0ubuntu3
> sudo apt-get install libc-bin=2.35-0ubuntu3 libc6=2.35-0ubuntu3
> sudo apt-get install libc-bin=2.35-0ubuntu3 libc6=2.35-0ubuntu3
> ldd --version
> sudo apt-get install libc-bin=2.35-0ubuntu3 libc6=2.35
> AmneziaVPN

```
/opt/AmneziaVPN/client/bin/AmneziaVPN: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/AmneziaVPN/client/bin/AmneziaVPN)
/opt/AmneziaVPN/client/bin/AmneziaVPN: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/AmneziaVPN/client/bin/AmneziaVPN)
/opt/AmneziaVPN/client/bin/AmneziaVPN: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/AmneziaVPN/client/bin/AmneziaVPN)
/opt/AmneziaVPN/client/bin/AmneziaVPN: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/AmneziaVPN/client/bin/AmneziaVPN)
/opt/AmneziaVPN/client/bin/AmneziaVPN: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /opt/AmneziaVPN/client/bin/AmneziaVPN)
```

### :question: Debian GNU/Linux 12 Bookworm
I am not sure there. I didn't have a good template for Debian 12

### :heavy_check_mark: Debian GNU/Linux 11 (bullseye)
No problems

**Comment by im7mortal** [comment]
It would be nice to have the snap package for Amnezia. It would make comfortable installation for many distros and many distros versions. 
Fedora like could then continue to use AmneziaInstaller

**Comment by pokamest** [comment]
We have uploaded 3.0.8 Linux release, please test it
https://github.com/amnezia-vpn/amnezia-client/releases/tag/3.0.8
