### ISSUE TITLE
Bug: Cannot connect to server from Android client app.

### ISSUE THREAD

**Issue by Steindvart** [amnezia-vpn/amnezia-client#267]
The steps to reproduce the bug are as follows:
1. A connection setting is added (_Proto: OpenVPN_)
2. Press the center button "Connect".
3. The connection attempt is immediately reset and no connection is made.

Environment:
- Samsung M31 (SM-M315F/DSN)
- Android 12
- Installed from "Google Play"

And this behavior is repeated all the time, not allowing to use VPN from mobile device.

Logs of this behavior: [AmneziaVPN.log](https://github.com/amnezia-vpn/amnezia-client/files/12225575/AmneziaVPN.log)

**Comment by Bushroott** [comment]
Same bug on "сlear" Android 12 (generic China phone). Ver 2.1.2 work well.

**Comment by arigatory** [comment]
Looks as if a provider somehow blocks the connection

**Comment by unlive74** [comment]
If you exit the application (using the exit button), it starts working correctly.

**Comment by Steindvart** [comment]
@arigatory 
> Looks as if a provider somehow blocks the connection

No. The same connection (network, provider, VPN server, protocol, etc.) from another device works fine.

**Comment by Steindvart** [comment]
@unlive74 
> If you exit the application (using the exit button), it starts working correctly.

I tried to do this. It didn't help :[ Bug playback has been preserved.

**Comment by arigatory** [comment]
> @arigatory 
> > Looks as if a provider somehow blocks the connection
> 
> No. The same connection (network, provider, VPN server, protocol, etc.) from another device works fine.
> 

Both devices have the same TTL or maybe one of the devices is used as a hot-spot?

**Comment by mrg1971** [comment]
Similar behavior...
Android client (v. 3.0.10 from Google Play) fails to connect using the configuration shared from Windows version (which works fine). OpenVPN over Cloak. On Androind the attempt to connect never ends up, just keeps on trying forever showing the animation. This reproduces on two phones (Samsung S22 and S21 FE, both on Androind 13)

**Comment by Steindvart** [comment]
After release [3.1.0](https://github.com/amnezia-vpn/amnezia-client/releases/tag/3.1.0 ) the problem is not reproducible, and I can use AmneziaVPN on my device correctly. Who had the same issue, check, everything should be fine now.

Thanks to everyone involved! ❤️
