### ISSUE TITLE
Bug: Can't deploy anything on client v3.x

### ISSUE THREAD

**Issue by dadyarri** [amnezia-vpn/amnezia-client#280]
Server: Ubuntu 22.04 (minimized)
Client: v3.0.8 (Win, Android)

When trying to install ovpn+cloak, progressbar finishes, but after it nothing happened (stuck on screen of installation). But the same messages are written endlessly to the logs:

```
2023-08-10 20:17:09 debug ServerController::Run script
2023-08-10 20:17:09 debug pm_apt="/usr/bin/apt-get";\
if [[ -f "$pm_apt" ]]; then pm=$pm_apt; else exit; fi;\
if [[ ! -f "/usr/bin/sudo" ]]; then $pm update -y -q; $pm install -y -q sudo; fi;\
sudo fuser /var/lib/dpkg/lock-frontend
2023-08-10 20:17:09 debug SSH chanel opened
2023-08-10 20:17:09 debug ServerController::runScript finished
```

**Comment by michaelkhabarov** [comment]
Same issue with Debian 11 server and 3.0.8 client on Mac

**Comment by dadyarri** [comment]
Problem not only with `onlyvpn_cloak` scripts, but with `dns` too. Freezes with same error. Probably somewhere in preparation steps

**Comment by dadyarri** [comment]
Seems like problem is somewhere here:

https://github.com/amnezia-vpn/amnezia-client/blob/34a228adbe74c0c0deed1d874f19f640fbfa0e72/client/server_scripts/check_server_is_busy.sh#L3-L4

But `fuser` is installed and manually this script executes successfully

**Comment by pokamest** [comment]
Please check fixes in https://github.com/amnezia-vpn/amnezia-client/actions/runs/5847886029

**Comment by dadyarri** [comment]
Configured server on Win v3.0.9 successfully, connected successfully
Tested on Android v3.0.8, connected successfully

**Comment by AriesAlex** [comment]
for me installing fsuser via psmisc helped
sudo apt install -y psmisc
