### ISSUE TITLE
iOS client OpenVPN over cloak hangs and does nothing.

### ISSUE THREAD

**Issue by Trogvars** [amnezia-vpn/amnezia-client#294]
Debian 12 Server +Android and Windows client works fine, but iOS client hangs up and does nothing.
When I press connect it flashes once and stands grey as not active and doesn't respond after that.

![photo_2023-08-21_14-35-20](https://github.com/amnezia-vpn/amnezia-client/assets/51442309/9a19db0b-d0de-45b0-a310-9d9547df319a)

**Comment by pokamest** [comment]
Check please 3.0.9 release for iOS

**Comment by Trogvars** [comment]
> Check please 3.0.9 release for iOS

Confirm it works now. But should press twice. First time it does nothing again, but then connects as it should.

**Comment by Trogvars** [comment]
Resolved with 3.0.9
