### ISSUE TITLE
Option "selected sites" doesn't work in Windows Client 3.0.8

### ISSUE THREAD

**Issue by Trogvars** [amnezia-vpn/amnezia-client#295]
Options "Selected site" and "Except selected sites" doesn't work at all comparing with 2.1.2 version.
It doesn't depends what option is used when connecting to VPN - it always works like "For all connecctions".

**Comment by VitaleyUsa** [comment]
can approve the same behaviour
windows 11 22h2 x64

**Comment by Mapteg34** [comment]
approve same for ubuntu 20.04, amnezia 3.0.8

**Comment by pokamest** [comment]
Fixed in 4.2
