### ISSUE TITLE
Android Client 3.0.8 and 2.1.2 does not work

### ISSUE THREAD

**Issue by dmitriyteteruk** [amnezia-vpn/amnezia-client#297]
Hi! I've installed OpenVPN over ShadowSocks server and shared connection to Windows and Android devices. 
Windows works fine, while Android 13 (security update 01.07.2023).
Amnezia Client 3.0.8 - shows Connected, but no VPN symbol in notification tray and devices does not use VPN at all.
Amnezia Client 2.1.1 - shows Connected, but not traffic to any destinations.

**Comment by Rame956** [comment]
Same here

**Comment by fromage9747** [comment]
I can't even get it to scan the QR code or use the file generated byt the windows app

**Comment by pokamest** [comment]
@fromage9747 @Rame956 @dmitriyteteruk 
We discontinued support of versions 2.x
VPN services created and shared using AmneziaVPN 2.1 might not work on 3.x releases, we recommend to reinstall them using 3.1.0 - https://github.com/amnezia-vpn/amnezia-client/releases/tag/3.1.0

"Amnezia Client 3.0.8 - shows Connected, but no VPN symbol in notification tray and devices does not use VPN at all." - this issue seem to be fixed, please also check 3.1.0 release.

Also, we don't recommend ShadowSocks at the moment, as it has too many issues.
We will improve ShadowSocks no earlier than beginning of 2024.

**Comment by fromage9747** [comment]
@pokamest I was not using version 2.

Currently, I got my previous VPN implementation working again.  Will see how it goes before giving this another try.
