### ISSUE TITLE
Check port failed if sudo/lsof missing

### ISSUE THREAD

**Issue by Ratio2** [amnezia-vpn/amnezia-client#303]
Android 3.0.8

Without sudo/lsof stdout not empty and app think port used:
```
-bash: sudo: command not found
-bash: lsof: command not found
```

Fixed with: apt install sudo lsof

**Comment by pokamest** [comment]
Please check 3.1.0
https://github.com/amnezia-vpn/amnezia-client/releases/tag/3.1.0

**Comment by pokamest** [comment]
Fixed, please update to the latest release
