### ISSUE TITLE
Installation failed if fuser missing

### ISSUE THREAD

**Issue by Ratio2** [amnezia-vpn/amnezia-client#304]
Android 3.0.8

On my server fuser binary missing by default and installation hang

Fixed with: apt install psmisc

**Comment by Trogvars** [comment]
> Fixed with: apt install psmisc

Same.

**Comment by pokamest** [comment]
Please check 3.1.0
https://github.com/amnezia-vpn/amnezia-client/releases/tag/3.1.0
In the 3.1.0 psmisc should be installed automatically.
