### ISSUE TITLE
Duplicate client name in Clients Management

### ISSUE THREAD

**Issue by Ratio2** [amnezia-vpn/amnezia-client#306]
Android 3.0.8

Steps:
1. Setup openvpn over cloak on new server
2. Share openvpn over cloak to amnezia
3. In client Managements we see two clients with name "Client 0"

After some client renaming/deleting problem automatically fixed and client index increased

**Comment by Pashtetickus** [comment]
Hi.
Where did you find Clients Management? I'm using 4.0.8.6 client and trying to manage clients but can't find where they are.

**Comment by Ratio2** [comment]
> Hi. Where did you find Clients Management? I'm using 4.0.8.6 client and trying to manage clients but can't find where they are.

This functionality was in the previous version 3.0.8

**Comment by pokamest** [comment]
Client management implemented in 4.2.
Please update to the latest version.
