### ISSUE TITLE
Client for OpenWRT

### ISSUE THREAD

**Issue by halsoi** [amnezia-vpn/amnezia-client#309]
Hello, I'm trying to setting up shadowsocks + OpenVPN or shadowsocks +WireGuard on my OpenWrt 19.07.7 but it failed.

I'm copy settings from my Amnezia VPN but it's hard to understand for me what is root cause.

`Thu Aug 31 08:14:09 2023 daemon.notice openvpn(amnvpn)[19878]: TCP/UDP: Preserving recently used remote address: [AF_INET]127.0.0.1:8585
Thu Aug 31 08:14:09 2023 daemon.notice openvpn(amnvpn)[19878]: Socket Buffers: R=[87380->87380] S=[16384->16384]
Thu Aug 31 08:14:09 2023 daemon.notice openvpn(amnvpn)[19878]: Attempting to establish TCP connection with [AF_INET]127.0.0.1:8585 [nonblock]
Thu Aug 31 08:14:09 2023 daemon.err openvpn(amnvpn)[19878]: TCP: connect to [AF_INET]127.0.0.1:8585 failed: Connection refused
Thu Aug 31 08:14:09 2023 daemon.notice openvpn(amnvpn)[19878]: SIGUSR1[connection failed(soft),init_instance] received, process restarting`

Could we suppest to create amnezia client for Openwrt or some documentation on setting up shadowsocks + OpenVPN or shadowsocks +WireGuard (with plugins Cloak)

**Comment by pokamest** [comment]
AmneziaWG for openwrt - https://github.com/amnezia-vpn/amneziawg-openwrt
Also read our dev group in Telegram for more information.
