### ISSUE TITLE
Add kill-switch for Windows client

### ISSUE THREAD

**Issue by nashikhmin** [amnezia-vpn/amnezia-client#310]
Please provide feature to block internet if vpn is disconnected not by user.
Or maybe you have ideas how to do it for Windows I can try to write this feature

**Comment by virussell** [comment]
Yes, this is very much missing in the app, this feature will prevent real IP leaks!

**Comment by eugene-beliaev** [comment]
Yeah that would be very useful

**Comment by pokamest** [comment]
Killswitch added in 4.3
