### ISSUE TITLE
Error on Sonoma 14.0 (23A339)

### ISSUE THREAD

**Issue by boyhood-fallers0v** [amnezia-vpn/amnezia-client#330]
**Error Description**.
Error appears after several uses on Mac os Sonoma 14.0 (23A339)

**Replay**.
1. Installed the programme
2. Started the VPN
3. Restarted the computer
4. When switching on, an error appears and the VPN does not switch on
5. Mount the installation image again
6. Uninstall the programme
7. Install the programme
8. VPN is working again, until the first overload.

**Log files**.
2023-09-16 13:22:14 debug IpcClient::init failed
2023-09-16 13:22:14 warning Error occurred when init IPC client

**Desktop (fill in the following information):**
 - OS: Sonoma 14.0 (23A339)
 - Version: 3.0.8
**Server (please fill in the following information):**.
 - OS: Ubuntu 22.04

**Comment by pokamest** [comment]
"Error occurred when init IPC client" this error indicates that the service AmneziaVPN-service is not started for some reason.
Have you disabled the AmneziaVPN-service (issued by Privacy Technologies) in the MacOS system settings?
Try to install latest release 3.1.0 - https://github.com/amnezia-vpn/amnezia-client/releases/tag/3.1.0

**Comment by boyhood-fallers0v** [comment]
> "Error occurred when init IPC client" this error indicates that the service AmneziaVPN-service is not started for some reason. Have you disabled the AmneziaVPN-service (issued by Privacy Technologies) in the MacOS system settings? 

Unfortunately I'm just a user and haven't found where to view the service, much less enable it.
If you give a recommendation on how to do it - would be grateful.
Version 3.1.0 is already installed, it has the same error.

**Comment by pokamest** [comment]
Check login items here
![image](https://github.com/amnezia-vpn/amnezia-client/assets/23482029/9d18b9a3-ea0c-4012-8dd3-5755a1e791e7)
