### ISSUE TITLE
 VPN does not work for selected sites on macOS system

### ISSUE THREAD

**Issue by OstriySous** [amnezia-vpn/amnezia-client#334]
**Describe the bug**
 VPN does not work for selected sites on macOS system
 
**To Reproduce**
1. Go to VPN
2. Click on use for selected sites
3. VPN isn't work for no one site...

**Expected behavior**

**Log files**

**Screenshots**
<img width="1908" alt="CleanShot 2023-09-19 at 21 28 04@2x" src="https://github.com/amnezia-vpn/amnezia-client/assets/67519432/d62a79a2-a84a-4a5a-92d3-32dc57c9c53a">
**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 13.5.2

**Additional context**

**Comment by pokamest** [comment]
Fixed in 4.x
