### ISSUE TITLE
3.1.0.1: cannot connect to my WG VPN server, created with Amnezia ver 2.x

### ISSUE THREAD

**Issue by pavelbel** [amnezia-vpn/amnezia-client#350]
Последняя версия 3.1.0.1 под Win x64 не может соединиться с моим давно работающим VPN сервером по протоколу WireGuard, который я создал в Amnezia версии 2.x. Версия 3.0.8.1 соединяется мгновенно и работает. Версия 3.1.0.1 бесконечно висит в состоянии "Подключение...".

**Desktop:**
 - OS: Windows 10 x64
 - версии Amnezia: x64 2.x (2.0.x или 2.1.x, не помню) для создания сервера, x64 3.1.0.1 и 3.0.8.1 для работы с ним

**Server:**
 - OS: Ubuntu-20.04-amd64
 - хостинг: RoboVPS

**Comment by pokamest** [comment]
It's known bug. Please try to clear Amnezia cache or reinstall WireGuard container
