### ISSUE TITLE
Self configured Cloak and openvpn.

### ISSUE THREAD

**Issue by itshikanov** [amnezia-vpn/amnezia-client#369]
hello. Can't choose another type of issue so this is not BUG. Sorry for this.

I'm configure my own cloak and openvpn with autentication ldap plugin.

I want use only amnezia client, not configured server from amnezia app.

It is possible to generate amnezia config like vpn:// for amnezia client from my configs for openvpn and cloak? Maybe a cli tool or something exist  ?

I'm asking because i'm not find the way how to insert cloak and openvpn config to amnezia-client

**Comment by pokamest** [comment]
You can use this tool https://github.com/amnezia-vpn/config-decoder
