### ISSUE TITLE
amnezia android client trying connecting to ssh without credentials

### ISSUE THREAD

**Issue by stanislavvv** [amnezia-vpn/amnezia-client#379]
Amnezia android client try to connect to ssh when connecting with shared connection (not server):

```
Oct 17 14:41:04 ftn sshd[2219949]: Invalid user  from x.x.x.x port 39894
Oct 17 14:41:04 ftn sshd[2219949]: Failed none for invalid user  from x.x.x.x port 39894 ssh2
```

If my wife and children connect to vpn in several minutes interval - fail2ban ban all connections to vds, because too many ssh errors from ip.

**To Reproduce**
1. create server (in my case - cloak+openvpn)
2. share connection (not server) to another client
3. connect with shared connection
4. see ssh logs

**Expected behavior**
No ssh interaction at all with shared connection.

**Comment by stanislavvv** [comment]
It was not "Share server", it was "Share for Amnezia". In decoded url i does not see user/password.

**Comment by stanislavvv** [comment]
In 4.0.8 only first connect try to login with empty user.
In Debian terminology — minor bug.

**Comment by stanislavvv** [comment]
Previous messsage - only for testing in same phone...
When i share connection ("Share for Amnezia") with another phone, take "Internal error" and in app log see:

2023-10-18 11:25:59 critical "Access denied for 'password'. Authentication that can continue: publickey,password"

and in server logs same records as in 1st message

**Comment by pokamest** [comment]
@stanislavvv please report if problem is still exists in latest release 4.4

**Comment by stanislavvv** [comment]
No ssh connects in vpn access. I think issue resolved.
