### ISSUE TITLE
Clients Management missing in 4.0.8

### ISSUE THREAD

**Issue by Ratio2** [amnezia-vpn/amnezia-client#401]
Without this functionality it is difficult to use for multiple clients. To revoke access, you need to go into the docker container, find and delete the certificate.

**Comment by papampi** [comment]
Can you explain how to add, remove, limit users?

**Comment by novichiv** [comment]
> Can you explain how to add, remove, limit users?
Similar to WireGuard

It's WireGuard with [extras](https://ntc.party/t/call-the-testers-amneziawg-protocol/6081)

You could examine it with:
`docker exec -it amnezia-awg sh -c "wg show"`

**Comment by Ratio2** [comment]
> Can you explain how to add, remove, limit users?

On each "share connection" amnezia generates new openvpn certificate.
Revoke: Use 3.1.0 version or https://github.com/amnezia-vpn/amnezia-client/blob/3.1.0/client/ui/pages_logic/ClientInfoLogic.cpp#L108

**Comment by pokamest** [comment]
Basic user management added to 4.2 release.
It's planned to implement more user management features.
