### ISSUE TITLE
Error when launch Amnezia on Android 9

### ISSUE THREAD

**Issue by carrot-cookie** [amnezia-vpn/amnezia-client#424]
**Describe the bug**
When I start the application, I got an error: "Your application encountered a fatal error and cannot continue", then i click OK and application closes.

**Log files**
[logcat.log](https://github.com/amnezia-vpn/amnezia-client/files/13321586/logcat.log)

**Screenshots**
![image](https://github.com/amnezia-vpn/amnezia-client/assets/56764829/01705c49-5172-4b79-8f6d-d003b86d5bd5)

**Smartphone:**
 - Device: Samsung Galaxy A8
 - OS: Android
 - Version 9

**Comment by carrot-cookie** [comment]
Amnezia version: 4.0.8.6
Installed from AmneziaVPN-4.0.8.6-armeabi-v7a.apk

**Comment by outspace** [comment]
Please try arm64-v8a version.

**Comment by carrot-cookie** [comment]
Yeah, all works for now. Thanks!
