### ISSUE TITLE
WG and AmneziaWG protocols not working on MacOS

### ISSUE THREAD

**Issue by lomik31** [amnezia-vpn/amnezia-client#425]
The Amnezia-wg protocol (as well as Wireguard) are not working. Connection to the server is made, but there is no access to the Internet. No pages load in the browser, ping command does not work (both by domain and ip). On other devices with the same server such problems are not observed
```
PING 1.1.1.1.1 (1.1.1.1.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
...
```

**To Reproduce:**
 1. Start the application
 2. Select AmneziaWG or Wireguard connection protocol
 3. Click "Connect"
 4. Wait for "Connected"
 5. Check Internet access

**Expected behavior**
 Sites in the browser and other programs access the internet through my server

**Log files**
[AmneziaVPN.log](https://github.com/amnezia-vpn/amnezia-client/files/13334305/AmneziaVPN.log)

**Screenshots**
<details>
<summary>Screenshots</summary>
<img width="384" alt="image" src="https://github.com/amnezia-vpn/amnezia-client/assets/38201662/bfc334e4-9434-4dd1-91a4-829418390946">
<img width="697" alt="image" src="https://github.com/amnezia-vpn/amnezia-client/assets/38201662/762da811-2db1-44a2-8a99-9b28bf7445fc">
</details>

**Desktop:**
 - Device: MacBook Air 2020 (M1)
 - OS: MacOS 13.6.1
 - App version: 4.0.8.6

**Server:**
 - OS: Ubuntu 22.04.2

**Comment by outspace** [comment]
Please check your DNS settings and its availability.
"45.90.28.61" "45.90.30.61" is setup in your app.

**Comment by lomik31** [comment]
I have the "Use AmneziaDNS" setting enabled. However, even after resetting DNS to default values, nothing has changed and there is still no internet access.

**Comment by outspace** [comment]
Please attach new log with "Use AmneziaDNS" option. 
Than try to ping 172.29.172.254 with connected VPN and "Use AmneziaDNS" option. 

> PING 1.1.1.1.1 (1.1.1.1.1): 56 data bytes

This adress is not IPv4.

**Comment by lomik31** [comment]
After a couple days of changing DNS servers, the problem resolved. Thanks for your help)
