### ISSUE TITLE
Invalid error handling of non-existent container

### ISSUE THREAD

**Issue by useribs** [amnezia-vpn/amnezia-client#450]
https://github.com/amnezia-vpn/amnezia-client/blob/08c506a48933e46eaeb105a2b3ae52237c547cd5/client/core/servercontroller.cpp#L166C28-L166C28

it expects "**Error:** No such container:"

I am not familiar with C, but this error message handling seems wrong, on my system i get the following error when trying to deal with non-existent container:
```
Error response from daemon: No such container: blad

# docker -v
Docker version 24.0.7, build afdd53b
```

Proposed fix: expect only **No such container:**   without Error string.

**Comment by lunardunno** [comment]
Is this the error text you get when running in the console? Or when running a script executed in sh or bash?

**Comment by useribs** [comment]
Should be fixed  #by:
https://github.com/amnezia-vpn/amnezia-client/pull/482

**Comment by useribs** [comment]
fix made it into dev?

**Comment by lunardunno** [comment]
yes.
