### ISSUE TITLE
Blocked access to my local addresses (192.168.0.1-255)

### ISSUE THREAD

**Issue by NeiroNext** [amnezia-vpn/amnezia-client#457]
**Describe the bug**
After turn on VPN I can't open any local sites or addresses

**To Reproduce**
1. Turn on Amnezia VPN
2. Open any local site or base route address, for example 192.168.0.1
3. Get error in browser

**Desktop:**
 - OS: Windows 11
 - Version: 23H2 

Wit other VPNs I already have access to my local addresses, now I cant' work without local servers that sad :c

**Comment by Ratio2** [comment]
https://github.com/amnezia-vpn/amnezia-client/issues/429
