### ISSUE TITLE
Windows Installer Problems

### ISSUE THREAD

**Issue by kamenkadmitry** [amnezia-vpn/amnezia-client#458]
Release AmneziaVPN_4.1.0.1_x64.exe 
Windows 10 Build 19045.3570 22H2

If you skip the problem, then the installation completes successfully and the program works. But apparently something is wrong.

![maintenancetool_SDnoypwTc2](https://github.com/amnezia-vpn/amnezia-client/assets/81700662/ea0abae3-06e4-449b-a9b9-caf93e1069c2)

![AmneziaVPN_4 1 0 1_x64(1)_MPSUqBgKe1](https://github.com/amnezia-vpn/amnezia-client/assets/81700662/c6284ff1-cf93-4a59-be19-f647e5ff9da0)

**Comment by pokamest** [comment]
Looks like service was not uninstalled correctly. If this happened, you can try to reboot, and then uninstall Amnezia, and then install from scratch.
