### ISSUE TITLE
Add the ability to send junk packets before the start of a session for the Wireguard protocol

### ISSUE THREAD

**Issue by evkravchenko** [amnezia-vpn/amnezia-client#525]
Please add the ability for the Wireguard client to send junk packets before the handshake, just like the AWG client does. This will allow the AmnesiaVPN client to be used for existing Wireguard installations, slightly extending their lifespan.

**Comment by Nethius** [comment]
implemented in https://github.com/amnezia-vpn/amnezia-client/releases/tag/4.5.3.0
