### ISSUE TITLE
AmneziaWG massive overhead. 

### ISSUE THREAD

**Issue by wyntrson** [amnezia-vpn/amnezia-client#526]
Hello, first I want to say thank you to people who created Amnezia. You are awesome. 

Second, my question is why AmneziaWG has 65% overhead. I know it is not a classing wireguard connection, but with wireguard, I was experiencing only 25-30% overhead on the same server. 

Is there a way to fix this?
Or maybe we should add the option in the client to address this?

**Comment by pokamest** [comment]
AmneziaWG has only few changes in comparing with WireGuard, which can not affect to the speed.
It may be confirmed if you will run it locally and measure speed from one docker container to another, or from host directly connected.
In real world connection speed controlled by your ISP, firewalls, government etc.

Also keep in mind that there is a difference between amneziawg-go implementation (based on wireguard-go) and kernel module implementation. When you installing AmneziaWG on your server by AmneziaVPN app, amneziawg-go installed, which may be slower than kernel module implementation on high speed connections and eat more CPU.
