### ISSUE TITLE
Dns change problem Windows 11 Openvpn over cloak

### ISSUE THREAD

**Issue by sis032** [amnezia-vpn/amnezia-client#535]
Hi. I have a problem. I changed DNS, but it doesn't have an effect. Please help me.
![image](https://github.com/amnezia-vpn/amnezia-client/assets/107427589/9037cecf-48d0-4130-bc60-8590da2ad9a4)
![image](https://github.com/amnezia-vpn/amnezia-client/assets/107427589/c2a1399e-7b10-4bf8-8745-ae10a1a5511d)
![image](https://github.com/amnezia-vpn/amnezia-client/assets/107427589/91105ef2-18af-4430-8c82-dccf706e08d6)

**Comment by outspace** [comment]
Please attach log file from AmneziaVPN client. 

Do you have predefined DNS server in tun interface settings?

**Comment by sis032** [comment]
Thank you. I have an outline program. AmneziaVPN used the Outline interface, that's why DNS changed to 1.1.1.1
![image](https://github.com/amnezia-vpn/amnezia-client/assets/107427589/67b3782d-6ee7-45ef-b63f-8949f2f8f1d2)
