### ISSUE TITLE
Mac ox tray icon is always white

### ISSUE THREAD

**Issue by nnbveh** [amnezia-vpn/amnezia-client#59]
On 2.0.8 icon doesn't change the color from gray to white and back anymore when you connect or disconnect, it's confusing, looks like VPN is active even when it's not...

thanks for the app ;)

Спасибо

**Comment by eugene-beliaev** [comment]
@nnbveh did it change color before 2.0.8?

**Comment by aleksholt** [comment]
Same problem

**Comment by eugene-beliaev** [comment]
Btw I've just reinstalled AmneziaWG protocol on my VPS and now everything's fine

**Comment by tconsta** [comment]
Checked on macos m1, @fameowner99 thanks a lot!

<img width="240" alt="image" src="https://github.com/amnezia-vpn/amnezia-client/assets/13377078/13b26b21-c3fd-4277-8ad1-22603cf825f2">

**Comment by pokamest** [comment]
Fixed in 4.5.1
