### ISSUE TITLE
qt is restricted from being downloaded in Russia. Replace.

### ISSUE THREAD

**Issue by rodionos** [amnezia-vpn/amnezia-client#612]
I am attempting to build the MacOS client and I'm running into issues with installing qt.

Their netops is specifically blocking Russia per qt forum. Such country level blocks are not mandated by any export regulations such as the ones applied to cryptographic tools and systems in the US. They are not providing specific references to any rules or regulations supporting their decision, I assume as a way to avoid any legal repercussions due to this questionable and a potentially illegal practice. I doubt they reversed any PRs in their open source or (and its dependencies) which were contributed by developers in Russia but qt feels free to block the very same developers at the whim of their political allegiances.

**Comment by pokamest** [comment]
You can install Qt using brew on MacOS

**Comment by rodionos** [comment]
`brew install qt` installs qt 6.6.1 on sonoma 14.3.1 which is the base framework. Nice... Is there a way to install the required modules without having to go through the qt web site?
