### ISSUE TITLE
Why did you disable downloading macOS version from AppStore (iPad apps)

### ISSUE THREAD

**Issue by ghost** [amnezia-vpn/amnezia-client#662]
**Describe the bug**
Can't update new version from AppStore

**To Reproduce**
1. Go to 'AppStore'
2. Click on 'Updates'
3. Click on Amnezia update

**Expected behavior**
Update installs and works as expected

**Log files**
Attach log files to help explain your problem.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.2.1

**Additional context**
App has been installed using AppStore, within 'apps for iPad' tab, but currently if I search for Amnezia, client not found also in apps for iPad.

**Comment by isamnezia** [comment]
There were complaints from users. Now we have returned it back to the App Store on Mac. If possible, please tell us about problems if they arise.

**Comment by ghost** [comment]
Updated successfully, thank you!
