### ISSUE TITLE
"Docker failed" while installing on Ubuntu 18.04.6

### ISSUE THREAD

**Issue by peresmeshnikov** [amnezia-vpn/amnezia-client#67]
Tried to install VPN via "Setup Wizard" on local VM with Ubuntu 18.04.6 runned on HyperV and got this error
![изображение](https://user-images.githubusercontent.com/64947180/163682635-6ecda3ca-861e-4bdd-aa6a-745706726ae1.png)
Same with Ubuntu 20.04
What I 'm doing wrong?

**Comment by peresmeshnikov** [comment]
Может дело в этом:
"Клиент подключается к вашему серверу по SSH, устанавливает Docker, если он ещё не установлен, и запускает серверные контейнеры Amnezia. Пока поддерживается только Ubuntu/Debian (нужен apt install docker-io)."

а должно же быть apt install docker.io
Если руками так поставить докер, то установка дальше продолжается успешно.
Если кто читает вообще issue здесь...

**Comment by pokamest** [comment]
Спасибо за репорт!
Планируем в скором времени взяться за issues

**Comment by motikolorado** [comment]
<img width="1440" alt="Screen Shot 2022-08-04 at 1 04 01 PM" src="https://user-images.githubusercontent.com/83591079/182919904-38fe3890-2cb1-45c8-b0f9-5dd27a300dca.png">
Macbook OS Monterey 2022. This error shows up. Please help... I have docker installed a long time ago. I have also updated my docker version and still the same error.

**Comment by Nethius** [comment]
Hi @peresmeshnikov @motikolorado It looks like you are connecting to the server with a user who is prompted for a password for sudo . For successful configuration, you need to connect as root or a user who does not have a password for sudo

**Comment by motikolorado** [comment]
@Nethius please how do i connect as root on mac

**Comment by Nethius** [comment]
> @Nethius please how do i connect as root on mac

https://superuser.com/questions/555810/how-do-i-ssh-login-into-my-mac-as-root maybe this will help

**Comment by john4669** [comment]
I have an Ubuntu 20.04 server at home with a dedicated IP address.  I set up a user with sudo privileges and get the same 'Docker Failed" error as the OP when trying to connect from an  Android client.  One comment says you need a root user who does not have a password.  That opens up such a security problem for my server as to make this not worth it.  Is there any alternative?

**Comment by pokamest** [comment]
> I have an Ubuntu 20.04 server at home with a dedicated IP address. I set up a user with sudo privileges and get the same 'Docker Failed" error as the OP when trying to connect from an Android client. One comment says you need a root user who does not have a password. That opens up such a security problem for my server as to make this not worth it. Is there any alternative?

No, you need to provide to Amnezia either root (with password or key), either other user (with password or key), which is not asking password for sudo.

About the error 'Docker Failed" - could you please share part of your log with this error?

**Comment by pokamest** [comment]
Issue was closed due to lack of response
