### ISSUE TITLE
Интерфейс не влезает на экран. Масштаб > 125%, 1920x1080, Windows 11.

### ISSUE THREAD

**Issue by Kamareka** [amnezia-vpn/amnezia-client#68]
Windows 11. При установке масштаба интерфейса > 125% и установленном разрешении экрана 1920х1080 интерфейс программы не помещается целиком на экране. При этом нет возможности прокрутки в окне.

**Comment by pokamest** [comment]
Please check 3.1.0 release
https://github.com/amnezia-vpn/amnezia-client/releases/tag/3.1.0
