### ISSUE TITLE
Android app не принимает .ovpn конфиги

### ISSUE THREAD

**Issue by inhale4sl** [amnezia-vpn/amnezia-client#724]
**Describe the bug**
В документации сказано, что амнезия принимает .von, .conf и .ovpn конфиги. Однако, при выборе .ovpn файла приложение просто переходит на предыдущий экран. 

**To Reproduce**
1. Открыть апп
2. Выбрать 'у меня есть данные для подключения'
3. Выбрать 'открыть файл конфига...'
4. Выбрать .ovpn файл
5. Оказаться на п.3

**Expected behavior**
Ожидается, что openvpn коннекшн добавится и будет работать.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7t
 - OS: Android 12
 - Version 4.4.0.0

**Additional context**
В приложение для macOs эти же конфиги работают без проблем.

**Comment by Nethius** [comment]
#735

**Comment by Nethius** [comment]
fixed in https://github.com/amnezia-vpn/amnezia-client/releases/tag/4.5.3.0
