### ISSUE TITLE
Optional disabling of the Kill-Switch feature

### ISSUE THREAD

**Issue by iriabaka** [amnezia-vpn/amnezia-client#742]
Before AmneziaVPN 4.3.0.0 I could use it with another VPN (for my work) and everything worked perfectly, but after that my second VPN stopped working properly when I connect to AmneziaVPN first.
I assume it's because of the kill switch feature.
Could you make this parameter optional with the ability to disable it if not needed?

**Comment by iriabaka** [comment]
If you manually remove pf rules, it starts working.
```shell
################
# List pf rules
################
sudo pfctl -a 'amn/*' -s rules

##################
# Remove pf rules
##################
sudo pfctl -a 'amn' -F all

test -f '/Applications/AmneziaVPN.app/Contents/MacOS/pf/pf.token' \
  && sudo pfctl -X `cat '/Applications/AmneziaVPN.app/Contents/MacOS/pf/pf.token'` \
  && sudo rm -rf '/Applications/AmneziaVPN.app/Contents/MacOS/pf/pf.token'

sudo test -f /etc/pf.conf \
  && sudo pfctl -F all -f /etc/pf.conf
```

**Comment by JackBekket** [comment]
Faced same issue

I am using tailscale as work VPN and if I connected (or simply launch AmneziaVPN app) -- it stopped working if Amnezia is active

Actually I cannot even use a normal connection when Amnezia VPN is *not connected* but app is launched

**Comment by outspace** [comment]
please check version with killSwitch toggle from #746 
You can download AmneziaVPN installer from github actions and approve fix.

**Comment by iriabaka** [comment]
> please check version with killSwitch toggle from #746 You can download AmneziaVPN installer from github actions and approve fix.

Everything works great on mac 👍 
Thanks a lot.

**Comment by iriabaka** [comment]
I suppose the issue can be closed after merging PR.
