### ISSUE TITLE
MacOS: public key auth

### ISSUE THREAD

**Issue by juev** [amnezia-vpn/amnezia-client#75]
Hello!

I was tried setup my server with ssh-keys:
<img width="492" alt="keys" src="https://user-images.githubusercontent.com/114635/177350740-7fff4235-d990-4ce4-87a4-b3bb5bd99816.png">

After select Setup Wizard and other steps I got error:

<img width="503" alt="error" src="https://user-images.githubusercontent.com/114635/177350731-22854de9-f3cd-4db7-841b-407ed0651f9b.png">

As I can understand, Issue with key format, you dont use new line.

I know about #8 

And question, what ssh-keys I can use? Possible to use id_ed25519 format?

**Comment by dmiwell** [comment]
I have same issue. It works fine for my old key, which I don't even remember how was generated. I don't want to use this key.

I've tried to generate new with `-t rsa`, with `-t rsa -b 4096`, with `-t ed25519`, but none worked. All of them works fine with usual ssh client.

The old key has head:
```
-----BEGIN RSA PRIVATE KEY-----
```

New keys have head:
```
-----BEGIN OPENSSH PRIVATE KEY-----
```

Changing head to use word `RSA` for rsa keys does not make any difference too.

Also, maybe it's a good idea to add support of local path to private key for connection?

**Comment by lqdc** [comment]
Looks like the bug might be here:
https://github.com/amnezia-vpn/amnezia-client/blob/34a228adbe74c0c0deed1d874f19f640fbfa0e72/client/ui/qml/Pages/PageStart.qml#L277C9-L277C22
TextFieldType can not have multiple lines of text.

So the fix might be to change it to [TextAreaType](https://doc.qt.io/qt-5/qml-qtquick-controls-textarea.html)

**Comment by pokamest** [comment]
Please check 3.1.0 release
https://github.com/amnezia-vpn/amnezia-client/releases/tag/3.1.0
