### ISSUE TITLE
Importing a vpn:// file results in an error "Invalid configuration file"

### ISSUE THREAD

**Issue by buylife** [amnezia-vpn/amnezia-client#751]
4.5.0.0

Importing a vpn:// file results in an error "Invalid configuration file"

<img width="340" alt="Screenshot 2024-04-12 at 12 33 26" src="https://github.com/amnezia-vpn/amnezia-client/assets/1515897/783776c0-98b2-4159-a038-0d4ffe8a1055">

**Comment by pokamest** [comment]
Please check latest build from https://github.com/amnezia-vpn/amnezia-client/actions/runs/8681230181

**Comment by pokamest** [comment]
Fixed in the latest release https://github.com/amnezia-vpn/amnezia-client/releases/tag/4.5.3.0
