### ISSUE TITLE
(запрос на доработку) Изменение значка приложения MacOS

### ISSUE THREAD

**Issue by iKowex** [amnezia-vpn/amnezia-client#760]
Возможно ли изменить значок, так что бы он изменялся при подключении, как например в WG или Viscosity.
Как он будет изменятся, в принципе не имеет значения, затемняться, менять цвет или вообще меняться.

![photo_2024-04-18 17 17 13](https://github.com/amnezia-vpn/amnezia-client/assets/124404017/8eac9507-8887-46e0-b303-d4782cdbf8b0)
![photo_2024-04-18 17 17 07](https://github.com/amnezia-vpn/amnezia-client/assets/124404017/b04deb0f-86a7-4fb2-8000-3f366b300f14)

MacOS (12.7.4) 
Amnezia 4.4.0.0

**Comment by pokamest** [comment]
What is OS?

**Comment by iKowex** [comment]
В названии написано MacOS (12.7.4) Amnezia 4.4.0.0

**Comment by fameowner99** [comment]
это уже пофикшено
https://github.com/amnezia-vpn/amnezia-client/issues/59
попробуй какую-то последнюю сборку скачать из github actions

**Comment by iKowex** [comment]
Новее 4.4.0.0 в релизе нету.

**Comment by fameowner99** [comment]
попробуй перейти в Actions
<img width="1875" alt="image" src="https://github.com/amnezia-vpn/amnezia-client/assets/34045014/6fe5cb70-6669-4373-9084-600de3b8c403">
выбрать какую-то сборку и скачать версию под свою OS.
Там dev сборки и там уже есть фикс по иконке, а когда будет след официальный релиз, то там будет фикс тоже

**Comment by fameowner99** [comment]
например, вот https://github.com/amnezia-vpn/amnezia-client/actions/runs/8742163365

**Comment by iKowex** [comment]
Если бы еще знать как скачать сборку

**Comment by fameowner99** [comment]
просто перейди по ссылке, что я кинул
и нажми на скачку [AmneziaVPN_MacOS_installer](https://github.com/amnezia-vpn/amnezia-client/actions/runs/8742163365/artifacts/1426849823)

<img width="1668" alt="image" src="https://github.com/amnezia-vpn/amnezia-client/assets/34045014/2f52d0dc-e451-4a0c-a778-4c1f431bf81a">

**Comment by iKowex** [comment]
"Слона я и не заметил" 🤦🏻‍♂️ 
Спасибо!

**Comment by iKowex** [comment]
<img width="197" alt="Снимок экрана 2024-04-19 в 14 06 00" src="https://github.com/amnezia-vpn/amnezia-client/assets/124404017/b69e0ec8-5967-4443-b4b4-40b965053f53">

<img width="197" alt="Снимок экрана 2024-04-19 в 14 06 11" src="https://github.com/amnezia-vpn/amnezia-client/assets/124404017/6884dc56-ee4d-42f8-8a72-9dd09488300d">

<img width="281" alt="Снимок экрана 2024-04-19 в 14 08 42" src="https://github.com/amnezia-vpn/amnezia-client/assets/124404017/4e5b0bf7-dbfd-4d09-b393-bd422dcac01e">

Спасибо, ждем релиза.
