### ISSUE TITLE
debug IpcClient::init failed on Mac OS M3 after reboot

### ISSUE THREAD

**Issue by Dmitriy67Rus** [amnezia-vpn/amnezia-client#798]
It doesn't connect to any configured method after rebooting the laptop.
Only reinstalling the app helps.

1. Install the app
2. reboot your laptop on mac os m3
3. error 101. internal error

```
2024-05-08 08:02:25 info Logging has enabled on AmneziaVPN version 4.5.2.0 89703ba5
2024-05-08 08:02:25 info macOS 14.4 (x86_64)
2024-05-08 08:02:27 debug VpnConfigurator::getDnsForConfig "1.1.1.1" "1.0.0.1"
2024-05-08 08:02:27 debug "ConnectToVpn, Server index is 0, container is amnezia-awg, route mode is" Settings::VpnOnlyForwardSites
2024-05-08 08:02:27 debug IpcClient::init failed
2024-05-08 08:02:27 warning Error occurred when init IPC client
```

23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:54 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6030 arm64
macOS 14.1
Chip: Apple M3 Pro
Total Number of Cores: 12 (6 performance and 6 efficiency)
Memory: 18 GB

**Comment by arturfse** [comment]
Same issue

**Comment by pokamest** [comment]
Have you granted permissions to the AmneziaVPN login item (issued by Privacy Technologies)?

**Comment by Dmitriy67Rus** [comment]
> Have you granted permissions to the AmneziaVPN login item (issued by Privacy Technologies)?

Yes, indeed, background activity for" Privacy Technologies OU " was disabled in login objects. Enabling the slider helped, no more errors occurred, thank you! It's probably worth making some kind of notification to users on mac os that such permission needs to be granted.

**Comment by arturfse** [comment]
Still not working
<img width="475" alt="1" src="https://github.com/amnezia-vpn/amnezia-client/assets/51407990/b90694f0-7eea-4454-b4ba-005816dd0779">

**Comment by TheDeadStone** [comment]
> Still not working <img alt="1" width="475" src="https://private-user-images.githubusercontent.com/51407990/329230586-b90694f0-7eea-4454-b4ba-005816dd0779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMjI5OTAsIm5iZiI6MTcyNzAyMjY5MCwicGF0aCI6Ii81MTQwNzk5MC8zMjkyMzA1ODYtYjkwNjk0ZjAtN2VlYS00NDU0LWI0YmEtMDA1ODE2ZGQwNzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDE2MzEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZGIxMjUxZWRkMjA1YzA0MWFjYjUzYmZkMDY1NTIyMGQzMGFjNDlmNGZiMTQ4OTQzODExZGI4OTRmMTlkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fotesDk97tVlGontKihtKeP6JSAYIoPskLMRpg2mUQg">

disabling and enabling helped for me
