### ISSUE TITLE
Feature Request: Connect Using Domain

### ISSUE THREAD

**Issue by AnikinNN** [amnezia-vpn/amnezia-client#801]
In scenarios where a physical server, such as a NAS, is situated in a location with a dynamic IP address provided by the Internet Service Provider. However it is possible to configure a domain name using Dynamic DNS. It would greatly enhance the utility of such home servers to have the capability to serve as VPN hosts.

As my expertise in VPN protocols is limited, I seek clarification on the possibility of configuring an Amnezia server solely with a public domain name. If it's is possible, so maybe implement this feature

**Comment by AsenOsen** [comment]
It would be nice just to allow using hostname on server establishement view - now input box allow only IP format
![image](https://github.com/amnezia-vpn/amnezia-client/assets/2146615/f7e3bd87-6b23-4667-8243-2035208a9d2e)

**Comment by rasolAAaa** [comment]
باسلام خدمت دست اندرکاران برنامه روچشم

در تاریخ یکشنبه ۱۶ ژوئن ۲۰۲۴،‏ ۱۷:۵۸ Antochi Anton ***@***.***>
نوشت:

**Comment by mrgspeed** [comment]
yes , please please add this feature. i really need this because my serve rip address changes every few days.

**Comment by dev0nizer** [comment]
+1 on this feature. Would be nice to configure and connect clients using DNS instead of IP address, so I can move the server and it's IP transparently for clients

**Comment by sc999999** [comment]
The following is a workaround, as I too have been looking for a solution.

So how do you change the fixed IP address of the server without reinstalling the service, as many of us do not have fixed IP from our internet service providers?  For other VPN services, we can use DDNS to address this problem.

Let's say you are traveling, and suddenly your home IP address is changed by the internet service provider, and you have to set up a new Amnezia server all over again while away from your machine?

I just managed to change the fixed IP configuration to one that uses the DDNS instead.  The config files can be used on the android app, as well as on the Windows Wiresock program.

What you do is install the Amnezia server onto the linux machine (cannot avoid using fixed IP), then in your android app, you share the connection.  Choose Native AmneziaWG format for the output.  This will generate the connection information, and will allow you to copy the text, and save to a connection.CONF file (name.conf file, use whatever text editor that comes with your phone).

Then you modify this config file and replace the fixed public IP address of the server to your DDNS name instead.  Finally, you create a new connection in your android app, and choose this modified config file.  You will see that this created connection does not point to numerical IP address server, but your DDNS.  Now you can use this new connection to connect to your Amnezia server, and not worry about the numerical IP address changing.

Yes, you cannot avoid setting up your original server or if you need to do any sharing of or create new connections without the numerical IP, but at least once you set up all your connections, you won't need to worry about dynamically changing IP addresses.

For me, I don't want to leave the SSH port open on the server to the outside world as only root user can install or modify the Amnezia service.  Once I have done all the tinkering on the service, I stop port forwarding of the SSH port from my router.
