### ISSUE TITLE
Feature Request: Local proxy-only mode

### ISSUE THREAD

**Issue by cjmaxik** [amnezia-vpn/amnezia-client#802]
I am using AdGuard + Shadowsocks in local "Proxy only" mode on my Android phone, so I can block ads even with VPN enabled. It would be nice to have this feature in Amnezia client as well.

**Comment by sameronline** [comment]
Agreed that would be awesome +1

**Comment by cjmaxik** [comment]
I think this feature request was linked to #762 by mistake - it assumes an on-device proxy for the VPN connection, not the server proxy. Local to the _device_, not to the _server_. Not sure how to do it without significant time resources, Shadowsocks client for Android [uses `ss-local` for this](https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt).
SOCKS5 server service is surely nice to have, though.

**Comment by rbo23** [comment]
> Local to the _device_, not to the _server_

I agree this issue was closed by mistake. I personally need local proxy on PC client so much
