### ISSUE TITLE
Split tunnelling in IOS and MacOS for applications

### ISSUE THREAD

**Issue by slm-windforce** [amnezia-vpn/amnezia-client#819]
Hi! Are there plans to add such a feature since it works for Android devices and how soon?

 - Device: IPhone 12 
 - OS: IOS
 - Version 17.5.1

**Comment by pokamest** [comment]
Split tunneling is not supported by iOS platform.
Please ask Apple to enable this feature on iOS.
On MacOS - the same story when using VPN based on Network Extensions
