### ISSUE TITLE
Error: 1000

### ISSUE THREAD

**Issue by megaslowpoke** [amnezia-vpn/amnezia-client#823]
Version 4.5.3.0 (maybe earlier, I have not used it for a long time) for Android refuses to work (error 1000), when a domain name is indicated in the config, if it is changed to IP, then everything works.

It does not depend on the DNS settings, i.e. The program is not even trying to resolve the address.

**Smartphone:**
 - OS: Android 11
 - Version Amnezia: 4.5.3.0

**Comment by ShihabSoft** [comment]
I've the exact same issue. Been facing this issue for a while from multiple previous versions, not sure from which it started, but if I remember right it used work fine. Currently, I resolve the domain and put the IP in the config, it's annoying to do it everytime as the WG server has a dynamic IP.

**Comment by Paulo1312** [comment]
Hey!

I make small script and web service for changing web-domain address to ip address in config

[Here ](https://paulo1312.github.io/amcofixer/) is web service (But it on russian) 

And [here](https://github.com/Paulo1312/amcofixer) is script 

If it's necessary - i can also make desktop application or feature for Amnezia client
