### ISSUE TITLE
UX: "Connect" button on iOS is hard to tap, it's too high for my thumb to reach

### ISSUE THREAD

**Issue by v-karbovnichy** [amnezia-vpn/amnezia-client#827]
**Describe the bug**
I use my phone (iPhone 13 Pro) mostly with my right hand only, holding it from the bottom with my little finger. I find it hard to press the big round "Connect" button all the times I try to connect/disconnect the VPN.

**To Reproduce**
1. Open AmnesiaVPN app
2. Try to click on the "Connect" button.
3. Stretch my hand to click it, or move the phone lower in my hand, risking to drop it and break the screen.

**Expected behavior**
I can easily press the "Connect" button with my thumb after opening the app.

**Log files**
Not relevant.

**Screenshots**
Can't do exact screenshot from my phone (it shows just the black screen), here is something I found in google:
![image](https://github.com/amnezia-vpn/amnezia-client/assets/7301634/8f4af4ff-0497-454d-87a2-3ab3f80b12e4)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 16.0
 - Version: 4.5.4

**Server (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
Here are the info on UX I found relevant:
https://www.behance.net/gallery/148277855/Touch-Zones-and-Assumptions
https://www.businessinsider.com/smartphone-pinky-finger-dents-not-permanent-damaging-doctors-say-2021-11

**Comment by pokamest** [comment]
Thank you for your feedback. We understand your concern regarding the difficulty of pressing the "Connect" button on the AmnesiaVPN app when using your iPhone 13 Pro with one hand. However, we have a unified design approach for all platforms and devices of all sizes. We will not be developing separate applications with specific designs for each platform.

We appreciate your understanding and will consider your feedback for future updates to improve the overall user experience
