### ISSUE TITLE
SFTP Permission denied for custom user

### ISSUE THREAD

**Issue by maxbolgarin** [amnezia-vpn/amnezia-client#838]
**Describe the bug**
When I want to set up VPN server with user `amnezia`, I got the error: `ErrorCode: 402. Sftp error: Permission denied`

**To Reproduce**
1. `sudo adduser amnezia`
2. `sudo usermod -aG sudo amnezia`
3. Open Amnezia App -> I have the data to connect -> Configure your server
4. Enter IP, `amnezia` and password for user, press continue, select Medium -> Continue
5. After 5 sec of Installing got error `ErrorCode: 402. Sftp error: Permission denied`

**Expected behavior**
Installed server

**Log files**
My ssh config:
```
Include /etc/ssh/sshd_config.d/*.conf
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication yes
KbdInteractiveAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem	sftp	/usr/lib/openssh/sftp-server
```

**Desktop:**
 -  Mac OS Sonoma 14.3.1 (23D60)

**Server:**
 - Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64)

**Comment by pokamest** [comment]
What is Amnezia version?

**Comment by maxbolgarin** [comment]
> What is Amnezia version?

4.4.0.0

**Comment by pokamest** [comment]
In the 4.5.3 sftp is not more used for file transferring between server and client (it replaced by scp). Please update to 4.5.3.
