### ISSUE TITLE
Trouble with X-RAY in iOS

### ISSUE THREAD

**Issue by iamzvv** [amnezia-vpn/amnezia-client#843]
**Describe the bug**
When I try to activate XRAY in iOS I see an error that this type is not supported. But if I go to Settings - General - VPN settings and activate it, everything is ok. 

**Smartphone:**
 - Device: iPhone 14 Pro Max
 - OS: 17.5.1
 - Version: 4.5.4.2 (62c33e37)

**Server (please complete the following information):**
 - OS: Debian 11. 

**Additional context**
![IMG_2953](https://github.com/amnezia-vpn/amnezia-client/assets/109719485/2e84c79d-a710-485b-9c68-a922a4c48876)

![IMG_2955](https://github.com/amnezia-vpn/amnezia-client/assets/109719485/5e6be398-5d87-4e13-8c23-a541a90c648d)

**Comment by pokamest** [comment]
Xray is not available for iOS yet.
In the iOS VPN settings last VPN succeed configuration used, so it's not Xray protocol.
Please wait for release for iOS with Xray
