### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by x011** [amnezia-vpn/amnezia-client#846]
Hi,
I cannot find Amnezia on Android TV Google Playstore. Are there any plans to support Android TV?
Thank you.

**Comment by pokamest** [comment]
Did you tried install APK?
https://github.com/amnezia-vpn/amnezia-client/releases/tag/4.5.3.0

**Comment by pokamest** [comment]
See also https://github.com/amnezia-vpn/amnezia-client/issues/826

**Comment by iksent** [comment]
> Did you tried install APK?

I've tried all APKs from latest Release, none of them installed on my Xiaomi with Android TV :(

**Comment by Runinterface** [comment]
> Did you tried install APK? https://github.com/amnezia-vpn/amnezia-client/releases/tag/4.5.3.0

Iam installed this apk, it is doesnt work, movement with remote cotroller doesnt work. Iam connected mouse and setup amnezia, but vpn doesnt work. Thank you.
Pls add android tv support!
