### ISSUE TITLE
How do add a socks5 proxy in front of amnezia server?

### ISSUE THREAD

**Issue by zwl1619** [amnezia-vpn/amnezia-client#847]
How do add a socks5 proxy in front of amnezia server?
I have installed amnezia at local and server, it works successfully, I can access Internet like this:
```
amnezia local  -> amnezia server  -> target
```
Now I want to add a socks5 proxy, then access Internet like this:
```
amnezia local  -> amnezia server -> socks5proxy -> target
```
What should I do?

**Comment by pokamest** [comment]
We've added socks proxy container feature
https://github.com/amnezia-vpn/amnezia-client/pull/762
It will be available in the next release.
