### ISSUE TITLE
VPN configuration is not created in MacOs settings

### ISSUE THREAD

**Issue by kolotovalexander** [amnezia-vpn/amnezia-client#848]
The VPN configurator from Amnezia is not created in the MacOs settings. If you install Amnezia for iPad through the App Store, the program asks if you to add a configurator and it is added, but there is no such thing through the macOS desktop application, I tried both old and new versions downloaded from this repository.
<img width="1203" alt="image" src="https://github.com/amnezia-vpn/amnezia-client/assets/100124537/7b5375b7-e619-4287-8239-3cf7403e7fb4">

**Comment by pokamest** [comment]
Amnezia still not use NetworkExtension on MacOS, but use it's own service to run VPN.
We are planning to implement VPN by NetworkExtension on MacOS soon.

**Comment by webAmoeba** [comment]
@kolotovalexander did u solve? it used to work for me somehow. I reset the mac, and now it's not working

**Comment by kolotovalexander** [comment]
> @kolotovalexander did u solve? it used to work for me somehow. I reset the mac, and now it's not working

Unfortunately, no. I needed AmneziaVPN because of the Split tunneling function, but it does not work well as I wanted (I tried it on iOS, where the config is normally installed, the config is even installed on macOS if you download AmneziaVPN via the AppStore for iPad, but does not connect.

I tried to import the configuration into ShadowsocksX-NG, but it doesn't work very well either. Pictures do not upload or allow files to be uploaded.

**Comment by deloss-s** [comment]
In my case vpn connection doesn't even start, m3 pro, mac os 15.1 beta
It just doesn't react on clicking on "connect" button

**Comment by arozhankov** [comment]
Hi,
You're right, the macOS VPN profile could be better. I can't share the internet with other devices with a VPN profile.

**Comment by GrampusV** [comment]
When installing AmneziaVPN and adding configuration files WireGuard VPN, does not work. The configuration file does not load in the "VPN" setting on MacOS 15.5. Any ideas on how to fix this? The client version downloaded from GitHub is 4.8.5

**Comment by yagee** [comment]
Same here
