### ISSUE TITLE
Update app icon for macOS according to Big Sur specifications

### ISSUE THREAD

**Issue by rakleed** [amnezia-vpn/amnezia-client#85]
Could you please update the app icon for macOS according to Big Sur specifications?

More: https://developer.apple.com/design/human-interface-guidelines/app-icons#Platform-considerations

**Comment by pokamest** [comment]
App icons updated in the 3.0.8 release

**Comment by rakleed** [comment]
@pokamest it still doesn't meet Apple's guild lines to be square with rounded corners.
![Screenshot 2023-09-16 at 02 44 34](https://github.com/amnezia-vpn/amnezia-client/assets/19418601/113862df-57c4-4a78-964d-11947b32486c)
