### ISSUE TITLE
SSH private key is not accepted during server setup

### ISSUE THREAD

**Issue by trackadelsilent** [amnezia-vpn/amnezia-client#874]
**Describe the bug**
Configure your server returns 101 error code while using SSH private key.

**To Reproduce**
1. Go to 'Configure your server'
2. Fill server IP
3. Fill SSH username
4. Fill Password or SSH private key with contents like:
-----BEGIN OPENSSH PRIVATE KEY-----
....
-----END OPENSSH PRIVATE KEY-----
5. See error

**Expected behavior**
Server setup continues to the next step.

**Screenshots**
<img width="374" alt="Screenshot 2024-07-01 at 14 55 50" src="https://github.com/amnezia-vpn/amnezia-client/assets/72935259/f4ccc9dc-c90e-448a-b63f-4c56a58bec7f">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Sonoma 14.4.1

**Server (please complete the following information):**
 - OS: Debian GNU/Linux 12

**Comment by rustem-galeev** [comment]
so do you have some workaround for this problem?

upd: I don't know why but for me using ecdsa key instead of rsa works fine

**Comment by trackadelsilent** [comment]
Hello,

Yes, the solution was provided to us by support.

пт, 5 июл. 2024 г., 20:58 rustem-galeev ***@***.***>:

**Comment by wKich** [comment]
@trackadelsilent, could you please share what exactly solution was provided?

**Comment by trackadelsilent** [comment]
@wKich 
Hello,

The following answer helped us:
> Amnezia does not support all kinds of SSH keys, try using a key that was generated by one of these commands:
> ssh-keygen -t rsa -m PEM -b 2048
> ssh-keygen -t rsa -m PEM -b 3072
> ssh-keygen -t rsa -m PEM -b 4096
> ssh-keygen -t ed25519

We had to regenerate the key.

**Comment by nnseva** [comment]
Hi everybody,

It's not necessary to regenerate the OpenSSH private key, actually. The existing OpenSSH private key can be used to access Amnezia from the client if properly converted to the old-style SSH key.

Use PuTTY to convert keys. The OpenSSH ssh-keygen tool can't do it properly.

The following is a Linux (Ubuntu) way to convert the existing OpenSSH private key `~/.ssh/id_rsa`:

```sh
sudo apt-get install putty-tools
puttygen ~/.ssh/id_rsa -O private-openssh -o ~/.ssh/id_rsa.ssh2
```

Use the contents of the existing file `~/.ssh/id_rsa.pub` to fill in the root SSH access key on your virtual host.

Then use the contents of the output file `~/.ssh/id_rsa.ssh2` (although, you could name it as you wish) to put into the `password` field (copy&past for simplicity)
