### ISSUE TITLE
AmneziaVPN_4.5.3.0.dmg is old version 4.5.2.0 file in the last release 

### ISSUE THREAD

**Issue by nightfury96** [amnezia-vpn/amnezia-client#888]
**Describe the bug**
Hi.
https://github.com/amnezia-vpn/amnezia-client/releases/tag/4.5.3.0
On the page of the latest release, the Mac OS installation file (.dmg) is the wrong version for installation. It is an older file version (4.5.2.0) 
https://github.com/amnezia-vpn/amnezia-client/releases/download/4.5.3.0/AmneziaVPN_4.5.3.0.dmg
Please fix it.
Thanks.

**Comment by pokamest** [comment]
It was just a numbering issue.
4.6.0.3 release already here - https://github.com/amnezia-vpn/amnezia-client/releases/tag/4.6.0.3
