### ISSUE TITLE
the app on amazon fire tv stick does not see the remote control

### ISSUE THREAD

**Issue by unlive74** [amnezia-vpn/amnezia-client#913]
installed AmneziaVPN on fire tv stick from Amazon, to turn on VPN I had to connect a mouse - the application is not controlled by the remote. Please check?

**Comment by Nethius** [comment]
android tv support will be in this issue https://github.com/amnezia-vpn/amnezia-client/issues/946

**Comment by Mikeyeahh** [comment]
I cannot find The app on fire stick, how can install it?

**Comment by SchugyC** [comment]
Download the app with silk browser or jdownloader from https://github.com/amnezia-vpn/amnezia-client/releases
Interestingly enough I can't even navigate in the amnezia backup screen with adb-Mouse app from my phone. You need to enable development mode adb for that mouse functionality and it works with lots of apps.
