### ISSUE TITLE
Hangs on Android TV 11

### ISSUE THREAD

**Issue by shurrman** [amnezia-vpn/amnezia-client#916]
Hi!
Tried to install latest APK on Android TV 11
It starts, but hangs on the first screen ("I have config/I do not have config") - have to reboot the TV to get it back operational

**Comment by EddieOrbit** [comment]
Hi! Same problem

**Comment by EddieOrbit** [comment]
@shurrman Hi! I have a solution:
1) Instal native AmneziaWG on your TV from .apk - https://play.google.com/store/apps/details?id=org.amnezia.awg
2) Create config for original AmneziaWG format (extension .conf)
3) Add config in app AmneziaWG
4) Connect and enjoy

**Comment by Nethius** [comment]
android tv support will be in this issue https://github.com/amnezia-vpn/amnezia-client/issues/946
