### ISSUE TITLE
[Feature Request] XRAY custom port (reverse proxy)

### ISSUE THREAD

**Issue by BlackWolfWoof** [amnezia-vpn/amnezia-client#930]
I have a reverse proxy running under port 443.
XRAY can therefore NOT use port 443.
I'd like to choose a custom port, that way i can re-map it to use my reverse proxy which my reverse proxy internally moves to xray-container:4443 as example.
![Screenshot_2024-08-04-22-22-01-63_c070da9001a1faa552ad1af3a9c1a6ed.jpg](https://github.com/user-attachments/assets/8ef78da1-7073-4f97-8638-aff9742b0097)

**Comment by Nethius** [comment]
will be added in this branch https://github.com/amnezia-vpn/amnezia-client/tree/feature/xray-custom-port
