### ISSUE TITLE
xray and nginx

### ISSUE THREAD

**Issue by Dmitrium12** [amnezia-vpn/amnezia-client#932]
I have been using your client successfully for a long time. Recently, I needed to set up Xray VPN, but my server is already running Nginx, which occupies port 443. I understand that I could remove Nginx to make it work, but I would prefer to keep Nginx and configure Xray VPN to run through it. Is this possible?

**Comment by KLcpb** [comment]
Hello, Did you resolve this problem?
I have the same situation.

**Comment by DiFuks** [comment]
As far as I understand, the developers have added a corresponding setting https://github.com/amnezia-vpn/amnezia-client/issues/930

**Comment by Dmitrium12** [comment]
> Hello, Did you resolve this problem?
> I have the same situation.
> 

Yes, everything worked thanks to the latest update.
