### ISSUE TITLE
OpenVPN over Cloak UDP option grayed out

### ISSUE THREAD

**Issue by AR45H** [amnezia-vpn/amnezia-client#939]
**Describe the bug**
Can not change OpenVPN protocol from TCP to UDP in settings

**To Reproduce**
1. Go to OpenVPN over Cloak settings
2. Click on OpenVPN
3. Select UDP Network Protocol
4. The selection is grayed out

**Expected behavior**
TCP/UDP Selection should work normally

**Log files**
N/A

**Screenshots**
![image](https://github.com/user-attachments/assets/f9cace72-640c-4ddf-994b-79c3638ec55a)

**Desktop (please complete the following information):**
 - OS: Win11
 - Version 23H2 (Build 22631.3007)

**Smartphone (please complete the following information):**
N/A

**Server (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by Nethius** [comment]
OpenVPN in OpenVPN over Cloak work only in tcp mode

**Comment by AR45H** [comment]
> OpenVPN in OpenVPN over Cloak work only in tcp mode

Okay well, is it a technical impossibility of the OpenVPN over Cloak? Or it hasn't been attempted before? 
Thanks for the reply.
