### ISSUE TITLE
Allow domain names and ipv6 as server addresses

### ISSUE THREAD

**Issue by amzaf** [amnezia-vpn/amnezia-client#948]
**Describe the bug**
In Configure Your Server section, please allow flexibility in specifying the server address. Currently only ipv4 is acceptable. I would like you to expand the choice to any of the ipv4, ipv6, and domain names as the server address.
<img width="380" alt="Screenshot 2024-08-07 at 00 08 37" src="https://github.com/user-attachments/assets/60de9068-a4e3-455f-924e-79ff5ed1bec8">

**To Reproduce**
1. Go to + menu, then configure your server
2. Click on Server ip address

**Expected behavior**
I would like to be able to enter the server address in any of the ipv4, ipv6 and domain name formats

**Log files**
Attach log files to help explain your problem.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 2.1.2]

**Smartphone (please complete the following information):**
 - Device: Macbook Pro
 - OS: macOS 
 - Version 14.6

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]

**Additional context**

**Comment by Nethius** [comment]
duplicate https://github.com/amnezia-vpn/amnezia-client/issues/892
