### ISSUE TITLE
Blinking of the "Preparing" label when pressing the "Connect" button.

### ISSUE THREAD

**Issue by steindvart** [amnezia-vpn/amnezia-client#956]
**Describe the bug**
When you click the main "Connect" button in the desktop client (Windows), there is a subtle change in the inscription to "Preparing...". This behavior has not happened before and it is confusing. There is a feeling of twitchiness and that the client is not working as it should.

**To Reproduce**
1. Launch AmneziaVPN windows client.
2. Configure server connection.
3. Click button "Connect".
4. Note that for a moment the button changes the label to "Preparing...", while violating the localization settings.

**Expected behavior**
The button changes its label to "Connecting..." without briefly switching to "Preparing...".

**Screenshots**
- Unexpected blinking of the "Preparing" label.
![2024-08-09_18-47](https://github.com/user-attachments/assets/4b283175-2e89-4ffd-95ec-ed85a47a4ab5)
- Video of behavior: https://github.com/user-attachments/assets/bf0efd3e-aea0-49cf-9049-dc59c207ed21

**Desktop**
 - OS: Windows 11
 - Version: AmneziaVPN Client 4.6.0.3 (Jul 8 2024)

**Comment by Nethius** [comment]
It's not a bug, it's just that the "Preparing..." stage is over very quickly.
