### ISSUE TITLE
Feature: add client management for Xray

### ISSUE THREAD

**Issue by Nethius** [amnezia-vpn/amnezia-client#960]
### for append client
1. add id generation when creating a connection config
2. add the user id to the server config
3. restart xray on the server
4. append client info to clients table

### for revoke client
1. remove the user id from the server config
2. restart xray on the server
3. remove client info from clients table

I think the workflow will be similar to adding/removing configs for wg/awg
wg config creation - https://github.com/amnezia-vpn/amnezia-client/blob/dev/client/configurators/wireguard_configurator.cpp
xray config creation - https://github.com/amnezia-vpn/amnezia-client/blob/dev/client/configurators/xray_configurator.cpp
user management - https://github.com/amnezia-vpn/amnezia-client/blob/dev/client/ui/models/clientManagementModel.cpp

**Comment by KiGamji** [comment]
please also consider adding the port change feature.

**Comment by Nethius** [comment]
> please also consider adding the port change feature.

it will be done in another issue

**Comment by alfirinoops** [comment]
Config that the client receives for connection, will be able to use on an unlimited number of devices? There are no restrictions on devices per one id?

**Comment by amnzam** [comment]
> Config that the client receives for connection, will be able to use on an unlimited number of devices? There are no restrictions on devices per one id?

Hello. There are no restrictions on qty of devices with Xray.

**Comment by mrdrprofuroboros** [comment]
Hey guys! any news here? When would it be possible to manage users with xray?

**Comment by iriswolf** [comment]
When will this be done?

**Comment by salotor** [comment]
In the waiting room

**Comment by paldeflex** [comment]
any news?

**Comment by DmitriyFrolov2** [comment]
Do you have any information about when it will be implemented?

**Comment by Selithrarion** [comment]
still no users in xray tab

**Comment by Arkemlar** [comment]
I use android version and it works
