### ISSUE TITLE
Doesn't show users in XRay protocol

### ISSUE THREAD

**Issue by BazZziliuS** [amnezia-vpn/amnezia-client#962]
**Describe the bug**
Doesn't show users in XRay protocol

**Expected behavior**
Users are visible

**Screenshots**
![image](https://github.com/user-attachments/assets/2c78d09e-82af-4df2-b3d9-92c4995400c8)
![image](https://github.com/user-attachments/assets/a7858e28-75f4-49e1-9502-5a9011eaf50e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2

**Server (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by Nethius** [comment]
https://github.com/amnezia-vpn/amnezia-client/issues/960

**Comment by bUmmy1337** [comment]
same
