### ISSUE TITLE
How to monitor vpn?

### ISSUE THREAD

**Issue by ostiwe** [amnezia-vpn/amnezia-client#970]
Hi, i have installed vpn from ios client, and on server have multiply docker containers so, im want to monitor clients and using traffic by prometheus (https://github.com/amnezia-vpn/amneziawg-exporter)

How i can do this?

**Comment by tiaga** [comment]
Hello,

First of all, this questions is more about AmneziaWG exporter itself and should be addressed to the corresponding repository. However, if check [README.md](https://github.com/amnezia-vpn/amneziawg-exporter/blob/main/README.md) you'll see, that it's possible to scrape metrics using the HTTP protocol from the 9351 TCP port. Note that this exporter is more suitable for big installations and returns only "current number of online users" and "daily active users".

**Comment by shipilovds** [comment]
@ostiwe you can look at the previous version of exporter at this point: https://github.com/amnezia-vpn/amneziawg-exporter/tree/36e4f9d1cad90b572f13274c72f120ae23478e6a
It contains more metrics. I think it is what you are looking for.
But if you want to use it with self-hosted version of amnezia server - it would be better if you add exporter to amneziawg image. You can ask anything. I can provide help.
