### ISSUE TITLE
MacOS app crashing on start

### ISSUE THREAD

**Issue by lexfreedomcom** [amnezia-vpn/amnezia-client#976]
**Describe the bug**
App Is crashing when I try to start it.

**To Reproduce**
1. Install app first time on you Mac 
2. Enable split tunneling
3. Start connection
4. Restart system
5. Click on application "Amnezia VPN" and start it

**Expected behavior**
Should open app UI window with connect button
BUT 
App is crashing and closing

**Log files**
__delegate_identifier__:Performance Diagnostics__:::____message__:This method should not be called on the main thread as it may lead to UI unresponsiveness

MacOS error: -67014

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Sonoma
 - Version 14.5

<img width="931" alt="Screenshot 2024-08-15 at 12 15 21" src="https://github.com/user-attachments/assets/2e256627-7a53-4f1c-826c-58fdbac0643c">
<img width="948" alt="Screenshot 2024-08-15 at 12 15 04" src="https://github.com/user-attachments/assets/09dee4f0-6ebf-438a-891f-eb730011ba71">

**Comment by lexfreedomcom** [comment]
App was working fine before enabling splittuneling and restarting Mac.

**Comment by maybephilipp** [comment]
Same issue on Mac OS 10.15.7

upd: 4.6.0.3 works fine
