### ISSUE TITLE
Can't connect to a server via Windows version

### ISSUE THREAD

**Issue by ghost** [amnezia-vpn/amnezia-client#982]
**Describe the bug**
I installed 4.5.3.0 desktop version for Windows. I press the connect button. After about 12 seconds i can see that i am connected, but i cannot visit the sites which are blocked in my country. However there is the internet connection and i can access the sites that are not blocked. At the same time the Android version works well. My laptop and my phone are connected to one and the same wi-fi router

**To Reproduce**
Download 4.5.3.0 desktop version for desktop and big button to try to connect to a server.

**Expected behavior**
VPN connection

**Log files**
[AmneziaVPN.log](https://github.com/user-attachments/files/16638761/AmneziaVPN.log)

**Desktop:**
 - OS: Windows 11
 - Version 23H2, OS Build 22631.4037

**Server:**
 - OS: Ubuntu 22.04

**Additional context**
I first tried to use 4.6.03 version but i haven't managed to fix the issue with appearing "error code 103: background service not running" message after pressing the connection button.

**Comment by CymraegKid** [comment]
Also upon installing i saw this message:
![изображение](https://github.com/user-attachments/assets/8621fb09-c844-4998-ae59-9d28072c3f13)

**Comment by ghost** [comment]
Here's my network settings in windows with turned on VPN:
![изображение](https://github.com/user-attachments/assets/7fedb28a-5fb2-4aaf-8026-afaaee4cdb0d)

**Comment by CymraegKid** [comment]
I have found the reason of the issue ! Lately i have accidentally deleted my PATH environment variable. I just recovered it and now Amnezia works !

**Comment by ghost** [comment]
I have found the reason of the issue ! Recently i have accidentally deleted my PATH environment variable. I just recovered it and now Amnezia works !
