### ISSUE TITLE
Request: Admin users should be marked as ADMIN on the user list somehow

### ISSUE THREAD

**Issue by dillfrescott** [amnezia-vpn/amnezia-client#984]
This would be a good addition because right now you can't tell which user is an admin and which isnt.

**Comment by Nethius** [comment]
admin users have long been marked as admin on the user list page
![image](https://github.com/user-attachments/assets/c0478202-302c-4d2c-8a1b-8a27b2cb3798)

**Comment by dillfrescott** [comment]
Oh sorry, I always rename the user to something else. I meant as a tag that isn't just part of the name to be renamed.

**Comment by dillfrescott** [comment]
I have opened a new issue with better clarification on what I think would be best for the software! Please take a look! :)

**Comment by wokalek** [comment]
> admin users have long been marked as admin on the user list page ![image](https://private-user-images.githubusercontent.com/15364855/358911047-c0478202-302c-4d2c-8a1b-8a27b2cb3798.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDU4MzUsIm5iZiI6MTcyNDMwNTUzNSwicGF0aCI6Ii8xNTM2NDg1NS8zNTg5MTEwNDctYzA0NzgyMDItMzAyYy00ZDJjLThhMWItOGEyN2IyY2IzNzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA1NDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYTMxOWMyMzUxNzljZjlkMTVmZjMzYjdjOTMzZjE2ZjQyNGNmMGZhYjY2MDNjNzRiOTUyNDRkOWYxNzZiZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M0dfcfIdovfSjd_nnHqHYOVs9Kso82bhcxY0jcUmwF8)

You can rename profile and never know who is admin and who's not.
