### ISSUE TITLE
101 error while trying to apply ssh key

### ISSUE THREAD

**Issue by artstylee** [amnezia-vpn/amnezia-client#991]
**Describe the bug**
cannot use ssh key for login

**To Reproduce**
generate key
ssh-keygen -t rsa -C ""
sshd config permitrootlogin = yes

**Expected behavior**
can login with ssh key

**Screenshots**
![Снимок](https://github.com/user-attachments/assets/fda8e005-41ce-4567-be7d-573d389d511e)

**Desktop (please complete the following information):**
window 10 x64 amnezia 4.7

**Server (please complete the following information):**
debian 12

**Additional context**
i can intentionally pass wrong ssh key and will get 300 error

**Comment by wKich** [comment]
@artstylee, It seems rsa keys don't work https://github.com/amnezia-vpn/amnezia-client/issues/874#issuecomment-2211294428
