### ISSUE TITLE
Windows client - Split tunneling for applications

### ISSUE THREAD

**Issue by IdeaFixe** [amnezia-vpn/amnezia-client#999]
Please allow us to switch between whitelist and blacklist for split tunneling for applications in windows client (i.e. only tunnel Firefox while the rest of traffic rests untunneled).

Cheers!

**Comment by denmorgenshtern** [comment]
split tunneling didn't work at all on windows

**Comment by DarthPredator** [comment]
I would like to support this ticket.
Some of the apps I'm running (some games to be exact) are plainly refusing to connect when split tunneling is enabled with "run everything through VPN but this list" setting. And running them through VPN causes some serious matchmaking and connection issues.

**Comment by nxsofsys** [comment]
Same, app based split tunneling not working on Windows. Adding *.exe app to the black list does not work - app still works through VPN. Ver 4.8.1.9

**Comment by Nethius** [comment]
Whitelists for apps is implemented only on android, due to the peculiarities of implementation on windows this mode is not available

**Comment by DearFox** [comment]
> Whitelists for apps is implemented only on android, due to the peculiarities of implementation on windows this mode is not available

But TunnlTo can do this, so technically it is possible.

**Comment by DarthPredator** [comment]
> But TunnlTo can do this, so technically it is possible.

Like any other VPN client can do this. Previous VPN I used before its protocols were blocked over here did that no problem. Granted it was openvpn/wireguard one, but still...
